package site.addzero.rc

import org.springframework.boot.autoconfigure.AutoConfiguration
import org.springframework.boot.context.properties.EnableConfigurationProperties

@AutoConfiguration
@EnableConfigurationProperties(ScanControllerProperties::class)
class ExpressionScanAutoConfiguration
