rootProject.name = rootDir.name
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
plugins {
//  id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
  id("site.addzero.gradle.plugin.repo-buddy") version "+"
  id("site.addzero.gradle.plugin.addzero-git-dependency") version "+"
//  id("site.addzero.gradle.plugin.modules-buddy") version "+"
}



// >>> Gradle Module Sleep: On-Demand Modules (DO NOT EDIT THIS BLOCK) >>>
// Generated at: 2026-05-30T15:21:07.577882
// Loaded: 89, Excluded: 0, Total: 89
include(":lib:ksp:metadata:method-semanticizer:method-semanticizer-spi")
include(":lib:ksp:metadata:method-semanticizer:method-semanticizer-spi-helper")
include(":lib:tool-jvm:database:ddlgenerator")
include(":lib:tool-jvm:database:ddlgenerator-core")
include(":lib:tool-jvm:database:ddlgenerator-dialect-dm")
include(":lib:tool-jvm:database:ddlgenerator-dialect-h2")
include(":lib:tool-jvm:database:ddlgenerator-dialect-kingbase")
include(":lib:tool-jvm:database:ddlgenerator-dialect-mysql")
include(":lib:tool-jvm:database:ddlgenerator-dialect-oracle")
include(":lib:tool-jvm:database:ddlgenerator-dialect-postgresql")
include(":lib:tool-jvm:database:ddlgenerator-dialect-sqlite")
include(":lib:tool-jvm:database:ddlgenerator-dialect-sqlserver")
include(":lib:tool-jvm:database:ddlgenerator-dialect-taos")
include(":lib:tool-jvm:database:ddlgenerator-jdbc-adaptor")
include(":lib:tool-jvm:database:ddlgenerator-lsi-adaptor")
include(":lib:tool-jvm:database:mybatis-auto-wrapper")
include(":lib:tool-jvm:database:mybatis-auto-wrapper-core")
include(":lib:tool-jvm:database:tool-cte")
include(":lib:tool-jvm:database:tool-database-model")
include(":lib:tool-jvm:database:tool-mybatis")
include(":lib:tool-jvm:database:tool-sql")
include(":lib:tool-jvm:database:tool-sql-executor")
include(":lib:tool-jvm:database:tool-sql-injection")
include(":lib:tool-jvm:jimmer:jimmer-ext-dynamic-datasource")
include(":lib:tool-jvm:jimmer:jimmer-ext-lowquery")
include(":lib:tool-jvm:jimmer:jimmer-ktx-serializer")
include(":lib:tool-jvm:jimmer:jimmer-model-lowquery")
include(":lib:tool-jvm:json2kotlin-dataclass")
include(":lib:tool-jvm:netty-util")
include(":lib:tool-jvm:network-call:browser:tool-api-browser-automation")
include(":lib:tool-jvm:network-call:browser:ws-automation")
include(":lib:tool-jvm:network-call:chat:api-models-chat")
include(":lib:tool-jvm:network-call:music:api-music-spi")
include(":lib:tool-jvm:network-call:music:api-netease")
include(":lib:tool-jvm:network-call:music:api-netease-semantic-impl")
include(":lib:tool-jvm:network-call:music:tool-api-music-search")
include(":lib:tool-jvm:network-call:music:tool-api-suno")
include(":lib:tool-jvm:network-call:music:tool-music-design")
include(":lib:tool-jvm:network-call:tool-api-email")
include(":lib:tool-jvm:network-call:tool-api-maven")
include(":lib:tool-jvm:network-call:tool-api-ocr")
include(":lib:tool-jvm:network-call:tool-api-payment")
include(":lib:tool-jvm:network-call:tool-api-soft-download")
include(":lib:tool-jvm:network-call:tool-api-translate")
include(":lib:tool-jvm:network-call:tool-api-tyc")
include(":lib:tool-jvm:network-call:tool-api-tyc-hw")
include(":lib:tool-jvm:network-call:tool-api-video-parse")
include(":lib:tool-jvm:network-call:tool-api-video-search-and-download")
include(":lib:tool-jvm:network-call:tool-api-weather")
include(":lib:tool-jvm:stream-wrapper")
include(":lib:tool-jvm:tool-ai")
include(":lib:tool-jvm:tool-api-jvm")
include(":lib:tool-jvm:tool-area")
include(":lib:tool-jvm:tool-bean")
include(":lib:tool-jvm:tool-bytebuddy")
include(":lib:tool-jvm:tool-cli-repl")
include(":lib:tool-jvm:tool-common-jvm")
include(":lib:tool-jvm:tool-context")
include(":lib:tool-jvm:tool-creditcard")
include(":lib:tool-jvm:tool-curl")
include(":lib:tool-jvm:tool-docker")
include(":lib:tool-jvm:tool-email")
include(":lib:tool-jvm:tool-excel")
include(":lib:tool-jvm:tool-funbox")
include(":lib:tool-jvm:tool-handwriting")
include(":lib:tool-jvm:tool-io")
include(":lib:tool-jvm:tool-io-codegen")
include(":lib:tool-jvm:tool-jsr")
include(":lib:tool-jvm:tool-jvmstr")
include(":lib:tool-jvm:tool-log")
include(":lib:tool-jvm:tool-math")
include(":lib:tool-jvm:tool-minio")
include(":lib:tool-jvm:tool-modbus")
include(":lib:tool-jvm:tool-mqtt")
include(":lib:tool-jvm:tool-mybatis-generator")
include(":lib:tool-jvm:tool-pinyin")
include(":lib:tool-jvm:tool-reflection")
include(":lib:tool-jvm:tool-s3")
include(":lib:tool-jvm:tool-serial")
include(":lib:tool-jvm:tool-spctx")
include(":lib:tool-jvm:tool-spel")
include(":lib:tool-jvm:tool-spring")
include(":lib:tool-jvm:tool-ssh")
include(":lib:tool-jvm:tool-stm32-bootloader")
include(":lib:tool-jvm:tool-template-jte")
include(":lib:tool-jvm:tool-toml")
include(":lib:tool-jvm:tool-yml")
include(":lib:tool-kmp:koog")
include(":lib:tool-kmp:models:common:common-models")
// <<< Gradle Module Sleep: End Of Block <<<
