package site.addzero.network.call.tyc.utils

import com.alibaba.fastjson2.parseObject
import org.junit.jupiter.api.Test
import site.addzero.network.call.tyc.entity.search.SearchRes

class SearchUtilTest {

    @Test
    fun `test getBaseInfo withTycApi valid response`() {
        val searchCompany = TycApi().searchCompany("中洛佳")
//       SearchRes
        println()
    }

    @Test
    fun djasoidja(): Unit {
        val responseBody = """
           {
  "state" : "ok",
  "message" : "",
  "special" : "111",
  "vipMessage" : "",
  "isLogin" : 0,
  "data" : {
    "humanCount" : 0,
    "companyCount" : 4,
    "companyHumanCount" : 0,
    "modifiedQuery" : null,
    "companyList" : [ {
      "id" : 3398690435,
      "name" : "河南<em>中洛佳</em>科技有限公司",
      "type" : 1,
      "matchType" : "公司名称匹配",
      "base" : "河南",
      "legalPersonName" : "马丽北",
      "estiblishTime" : "2019-12-17 00:00:00.0",
      "regCapital" : "1000万人民币",
      "regStatus" : "存续",
      "score" : "73",
      "orginalScore" : "7332",
      "bonusScore" : "0",
      "companyScore" : "73",
      "historyNames" : "",
      "categoryCode" : "656",
      "industry" : null,
      "humanNames" : "李莹莹\t:#0\t;\t马丽北\t:#0\t;\t马丽北\t:#1\t;\t李莹莹\t:#1\t;\t",
      "trademarks" : null,
      "tmList" : null,
      "productList" : null,
      "usedBondName" : null,
      "bondName" : null,
      "bondNum" : null,
      "bondType" : null,
      "newtestName" : null,
      "regNumber" : "410394000177215",
      "orgNumber" : "MA47WC78-8",
      "creditCode" : "91410307MA47WC788D",
      "businessScope" : "信息系统集成服务;仪器仪表销售;办公设备销售;机械设备销售;电子产品销售;通讯设备销售;通信设备销售;办公用品销售;建筑材料销售;信息安全设备销售;安防设备销售;第一类医疗器械销售;第二类医疗器械销售;软件销售;技术服务;技术开发;技术咨询;技术交流;技术转让;技术推广;网络技术服务;信息技术咨询服务;网络与信息安全软件开发;软件开发;信息系统运行维护服务;计算机系统服务;安全技术防范系统设计施工服务;交通及公共管理用金属标牌制造;交通及公共管理用标牌销售;商务代理代办服务;凭营业执照依法自主开展经营活动;建筑智能化系统设计;依托实体医院的互联网医院服务;建设工程施工",
      "regLocation" : "河南省洛阳市太康路与汇通街交叉口大数据产业园综合楼四楼405室",
      "phone" : "037965199909\t;\t0379-65199909",
      "phoneList" : [ "0379-65199909" ],
      "phoneInfoList" : [ {
        "number" : "0379-65199909",
        "type" : "9",
        "label" : "2",
        "source" : null,
        "comment" : "固定电话或非大陆号码"
      } ],
      "businessItemList" : null,
      "phoneNum" : "0379-65199909",
      "logo" : "",
      "city" : "洛阳市",
      "district" : "洛龙区",
      "emails" : "hnzljkj@163.com\t;\t419569781@qq.com\t;\t41956781@qq.com\t;\tzlj65199909@163.com",
      "emailList" : [ "hnzljkj@163.com", "419569781@qq.com", "41956781@qq.com", "zlj65199909@163.com" ],
      "websites" : "",
      "hiddenPhones" : null,
      "abbr" : "",
      "tagList" : null,
      "companyType" : 1,
      "companyOrgType" : "有限责任公司\t;\t有限责任公司(自然人投资或控股)",
      "labelList" : null,
      "matchField" : {
        "field" : "公司简称",
        "content" : "河南<em>中洛佳</em>科技"
      },
      "latitude" : null,
      "longitude" : null,
      "legalPersonId" : "3398690439",
      "legalPersonType" : "1",
      "distance" : null,
      "categoryStr" : "软件和信息技术服务业",
      "isClaimed" : 0,
      "claimPkgType" : null,
      "realClaimPkgType" : null,
      "baiduUrl" : null,
      "isBranch" : 0,
      "alias" : "中洛佳",
      "claimInfo" : null,
      "hidden" : 0,
      "legalPersonShowStr" : "法定代表人",
      "regCapitalShowStr" : "注册资本",
      "estiblishTimeShowStr" : "成立日期",
      "multiMatchField" : [ {
        "field" : "商标信息",
        "content" : "<em>中洛佳</em>"
      }, {
        "field" : "公司简称",
        "content" : "河南<em>中洛佳</em>科技"
      } ],
      "labelListV2" : [ "高新技术企业", "科技型中小企业", "小微企业" ],
      "labelJsonList" : [ "{\"type\":1,\"value\":\"高新技术企业\"}", "{\"type\":1,\"value\":\"科技型中小企业\"}", "{\"type\":1,\"value\":\"小微企业\"}" ],
      "taxCode" : "91410307MA47WC788D",
      "socialSecurityStaff_num" : "21",
      "categoryCodeStd" : "651",
      "hasMorePhone" : null,
      "hasVideo" : null,
      "videoId" : null,
      "isRecommend" : null,
      "englishName" : "Henan Zhongluojia Technology Co., Ltd",
      "firstPositionShowStr" : "法定代表人",
      "secondPositionShowStr" : "注册资本",
      "firstPositionValue" : "马丽北",
      "secondPositionValue" : "1000万人民币",
      "bizType" : "7",
      "docFeature" : "{\"isFollowed\":0,\"isMonitored\":0,\"historyClicks\":0,\"byAnn\":0,\"timeClicks\":[0,0,1,1],\"byBaidu\":0}",
      "companyNum" : null,
      "department" : "",
      "illegalType" : "0",
      "targetGid" : "",
      "targetName" : "",
      "changeTime" : "",
      "isIn" : "",
      "mainId" : "",
      "targetRegCapitalAmount" : "",
      "targetRegCapitalCurrency" : "",
      "legalPerson" : "",
      "gidForB" : "3398690435",
      "geoLocation" : null,
      "websiteFilingCount" : 0,
      "repCurrency" : null,
      "province" : "00410311\t;\t00410300\t;\t00410000",
      "areaCodes" : [ "00410311", "00410300", "00410000" ],
      "address" : null,
      "establishmentTime" : "20191217",
      "icps" : null,
      "icp" : "",
      "changeRatio" : "",
      "afterRatio" : "",
      "changeAmt" : "",
      "registerInstitute" : "洛阳市洛龙区市场监督管理局",
      "companyScale" : "小型",
      "abstractsBaseInfo" : "河南中洛佳科技有限公司，成立于2019年，位于河南省洛阳市，是一家以从事软件和信息技术服务业为主的企业。企业注册资本1000万人民币，超过了94%的河南省同行，实缴资本447.5万人民币。",
      "financingRound" : "未融资",
      "staffNumReportYear" : 2024,
      "categoryCode2017List" : [ "I", "65", "656", "6560" ],
      "institutionTypeList" : [ "企业", "有限责任公司", "其他有限责任公司" ],
      "companyBrandInfo" : null,
      "companyGroupInfo" : null,
      "contantMap" : {
        "recallSrc" : "ES",
        "param_reg_capital" : "1000.0",
        "establish_time_long" : "1576512000000"
      },
      "companyPhoneBook" : {
        "type" : null,
        "friendName" : null
      },
      "companyQuestions" : {
        "logos" : null,
        "participantCount" : null,
        "textContent" : null,
        "qid" : null
      },
      "executive" : null,
      "noActualCapital" : null,
      "threeMonthsLawsuit" : null,
      "residentialBuilding" : null,
      "qualifiedFinancialProduct" : null
    }, {
      "id" : 6897025231,
      "name" : "河南<em>中洛佳</em>科技有限公司西工分公司",
      "type" : 1,
      "matchType" : "公司名称匹配",
      "base" : "河南",
      "legalPersonName" : "吕奕飞",
      "estiblishTime" : "2024-04-09 00:00:00.0",
      "regCapital" : "-",
      "regStatus" : "存续",
      "score" : "23",
      "orginalScore" : "2382",
      "bonusScore" : "0",
      "companyScore" : "23",
      "historyNames" : "",
      "categoryCode" : "653",
      "industry" : null,
      "humanNames" : "",
      "trademarks" : null,
      "tmList" : null,
      "productList" : null,
      "usedBondName" : null,
      "bondName" : null,
      "bondNum" : null,
      "bondType" : null,
      "newtestName" : null,
      "regNumber" : "",
      "orgNumber" : "MADGYA5U-5",
      "creditCode" : "91410303MADGYA5U5J",
      "businessScope" : "信息系统集成服务;信息技术咨询服务;网络与信息安全软件开发;信息系统运行维护服务;计算机系统服务;第一类医疗器械销售;第二类医疗器械销售;凭营业执照依法自主开展经营活动;依托实体医院的互联网医院服务",
      "regLocation" : "河南省洛阳市西工区衡山路与蔡岭路交叉口中弘凤凰谷产业园2号楼607室",
      "phone" : "15729104517",
      "phoneList" : [ "15729104517" ],
      "phoneInfoList" : [ {
        "number" : "15729104517",
        "type" : "9",
        "label" : "1",
        "source" : null,
        "comment" : "固定电话或非大陆号码"
      } ],
      "businessItemList" : null,
      "phoneNum" : "15729104517",
      "logo" : "",
      "city" : "洛阳市",
      "district" : "西工区",
      "emails" : "hnzljkj@163.com",
      "emailList" : [ "hnzljkj@163.com" ],
      "websites" : "",
      "hiddenPhones" : null,
      "abbr" : "",
      "tagList" : null,
      "companyType" : 1,
      "companyOrgType" : "有限责任公司\t;\t有限责任公司分公司(自然人投资或控股)",
      "labelList" : null,
      "matchField" : {
        "field" : "地址信息",
        "content" : "河南省<em>洛</em>阳市西工区衡山路与蔡岭路交叉口<em>中</em>弘凤凰谷产业园2号楼607室"
      },
      "latitude" : null,
      "longitude" : null,
      "legalPersonId" : "1840362298",
      "legalPersonType" : "1",
      "distance" : null,
      "categoryStr" : "软件和信息技术服务业",
      "isClaimed" : 0,
      "claimPkgType" : null,
      "realClaimPkgType" : null,
      "baiduUrl" : null,
      "isBranch" : 1,
      "alias" : "中洛佳",
      "claimInfo" : null,
      "hidden" : 0,
      "legalPersonShowStr" : "负责人",
      "regCapitalShowStr" : "注册资本",
      "estiblishTimeShowStr" : "成立日期",
      "multiMatchField" : [ ],
      "labelListV2" : [ "小微企业" ],
      "labelJsonList" : [ "{\"type\":1,\"value\":\"小微企业\"}" ],
      "taxCode" : "91410303MADGYA5U5J",
      "socialSecurityStaff_num" : "0",
      "categoryCodeStd" : "",
      "hasMorePhone" : null,
      "hasVideo" : null,
      "videoId" : null,
      "isRecommend" : null,
      "englishName" : null,
      "firstPositionShowStr" : "负责人",
      "secondPositionShowStr" : "企业类型",
      "firstPositionValue" : "吕奕飞",
      "secondPositionValue" : "有限责任公司分公司(自然人投资或控股)",
      "bizType" : "3",
      "docFeature" : "{\"isFollowed\":0,\"isMonitored\":0,\"historyClicks\":0,\"byAnn\":0,\"timeClicks\":[0,0,1,1],\"byBaidu\":0}",
      "companyNum" : null,
      "department" : "",
      "illegalType" : "0",
      "targetGid" : "",
      "targetName" : "",
      "changeTime" : "",
      "isIn" : "",
      "mainId" : "",
      "targetRegCapitalAmount" : "",
      "targetRegCapitalCurrency" : "",
      "legalPerson" : "",
      "gidForB" : "6897025231",
      "geoLocation" : null,
      "websiteFilingCount" : 0,
      "repCurrency" : null,
      "province" : "00410303\t;\t00410300\t;\t00410000",
      "areaCodes" : [ "00410303", "00410300", "00410000" ],
      "address" : null,
      "establishmentTime" : "20240409",
      "icps" : null,
      "icp" : "",
      "changeRatio" : "",
      "afterRatio" : "",
      "changeAmt" : "",
      "registerInstitute" : "洛阳市西工区市场监督管理局",
      "companyScale" : null,
      "abstractsBaseInfo" : "河南中洛佳科技有限公司西工分公司，成立于2024年，位于河南省洛阳市，是一家以从事软件和信息技术服务业为主的企业。",
      "financingRound" : "未融资",
      "staffNumReportYear" : 2024,
      "categoryCode2017List" : [ "I", "65", "653", "6531" ],
      "institutionTypeList" : [ "企业", "有限责任公司", "其他有限责任公司" ],
      "companyBrandInfo" : null,
      "companyGroupInfo" : null,
      "contantMap" : {
        "recallSrc" : "ES",
        "establish_time_long" : "1712592000000"
      },
      "companyPhoneBook" : {
        "type" : null,
        "friendName" : null
      },
      "companyQuestions" : {
        "logos" : null,
        "participantCount" : null,
        "textContent" : null,
        "qid" : null
      },
      "executive" : null,
      "noActualCapital" : null,
      "threeMonthsLawsuit" : null,
      "residentialBuilding" : null,
      "qualifiedFinancialProduct" : null
    }, {
      "id" : 5789105607,
      "name" : "河南<em>中洛佳</em>科技有限公司洛宁分公司",
      "type" : 1,
      "matchType" : "公司名称匹配",
      "base" : "河南",
      "legalPersonName" : "马丽北",
      "estiblishTime" : "2022-11-04 00:00:00.0",
      "regCapital" : "-",
      "regStatus" : "存续",
      "score" : "11",
      "orginalScore" : "1124",
      "bonusScore" : "0",
      "companyScore" : "11",
      "historyNames" : "",
      "categoryCode" : "653",
      "industry" : null,
      "humanNames" : "",
      "trademarks" : null,
      "tmList" : null,
      "productList" : null,
      "usedBondName" : null,
      "bondName" : null,
      "bondNum" : null,
      "bondType" : null,
      "newtestName" : null,
      "regNumber" : "410328000058959",
      "orgNumber" : "MA9MWLT5-0",
      "creditCode" : "91410328MA9MWLT50P",
      "businessScope" : "信息系统集成服务;电子产品销售;信息安全设备销售;软件销售;技术服务;技术开发;技术咨询;技术交流;技术转让;技术推广;软件开发;承接总公司工程建设业务;凭营业执照依法自主开展经营活动;建筑智能化系统设计",
      "regLocation" : "河南省洛阳市洛宁县城关镇永宁大道商务大厦八楼801室",
      "phone" : "13523625555",
      "phoneList" : [ "13523625555" ],
      "phoneInfoList" : [ {
        "number" : "13523625555",
        "type" : "1",
        "label" : "1",
        "source" : null,
        "comment" : "号码可正常联系"
      } ],
      "businessItemList" : null,
      "phoneNum" : "13523625555",
      "logo" : "",
      "city" : "洛阳市",
      "district" : "洛宁县",
      "emails" : "hnzljkj@163.com\t;\t419569781@qq.com",
      "emailList" : [ "hnzljkj@163.com", "419569781@qq.com" ],
      "websites" : "",
      "hiddenPhones" : null,
      "abbr" : "",
      "tagList" : null,
      "companyType" : 1,
      "companyOrgType" : "有限责任公司\t;\t有限责任公司分公司(自然人投资或控股)",
      "labelList" : null,
      "matchField" : {
        "field" : "地址信息",
        "content" : "河南省<em>洛</em>阳市<em>洛</em>宁县城关镇永宁大道商务大厦八楼801室"
      },
      "latitude" : null,
      "longitude" : null,
      "legalPersonId" : "3398690439",
      "legalPersonType" : "1",
      "distance" : null,
      "categoryStr" : "软件和信息技术服务业",
      "isClaimed" : 0,
      "claimPkgType" : null,
      "realClaimPkgType" : null,
      "baiduUrl" : null,
      "isBranch" : 1,
      "alias" : "中洛佳",
      "claimInfo" : null,
      "hidden" : 0,
      "legalPersonShowStr" : "负责人",
      "regCapitalShowStr" : "注册资本",
      "estiblishTimeShowStr" : "成立日期",
      "multiMatchField" : [ ],
      "labelListV2" : [ "小微企业" ],
      "labelJsonList" : [ "{\"type\":1,\"value\":\"小微企业\"}" ],
      "taxCode" : "91410328MA9MWLT50P",
      "socialSecurityStaff_num" : "0",
      "categoryCodeStd" : "",
      "hasMorePhone" : null,
      "hasVideo" : null,
      "videoId" : null,
      "isRecommend" : null,
      "englishName" : "Henan Zhongluojia Technology Co., Ltd. Luoning Branch",
      "firstPositionShowStr" : "负责人",
      "secondPositionShowStr" : "企业类型",
      "firstPositionValue" : "马丽北",
      "secondPositionValue" : "有限责任公司分公司(自然人投资或控股)",
      "bizType" : "0",
      "docFeature" : "{\"isFollowed\":0,\"isMonitored\":0,\"historyClicks\":0,\"byAnn\":0,\"timeClicks\":[],\"byBaidu\":0}",
      "companyNum" : null,
      "department" : "",
      "illegalType" : "0",
      "targetGid" : "",
      "targetName" : "",
      "changeTime" : "",
      "isIn" : "",
      "mainId" : "",
      "targetRegCapitalAmount" : "",
      "targetRegCapitalCurrency" : "",
      "legalPerson" : "",
      "gidForB" : "5789105607",
      "geoLocation" : null,
      "websiteFilingCount" : 0,
      "repCurrency" : null,
      "province" : "00410328\t;\t00410300\t;\t00410000",
      "areaCodes" : [ "00410328", "00410300", "00410000" ],
      "address" : null,
      "establishmentTime" : "20221104",
      "icps" : null,
      "icp" : "",
      "changeRatio" : "",
      "afterRatio" : "",
      "changeAmt" : "",
      "registerInstitute" : "洛宁县市场监督管理局",
      "companyScale" : null,
      "abstractsBaseInfo" : "河南中洛佳科技有限公司洛宁分公司，成立于2022年，位于河南省洛阳市，是一家以从事软件和信息技术服务业为主的企业。",
      "financingRound" : "未融资",
      "staffNumReportYear" : 2024,
      "categoryCode2017List" : [ "I", "65", "653", "6531" ],
      "institutionTypeList" : [ "企业", "有限责任公司", "其他有限责任公司" ],
      "companyBrandInfo" : null,
      "companyGroupInfo" : null,
      "contantMap" : {
        "recallSrc" : "ES",
        "establish_time_long" : "1667491200000"
      },
      "companyPhoneBook" : {
        "type" : null,
        "friendName" : null
      },
      "companyQuestions" : {
        "logos" : null,
        "participantCount" : null,
        "textContent" : null,
        "qid" : null
      },
      "executive" : null,
      "noActualCapital" : null,
      "threeMonthsLawsuit" : null,
      "residentialBuilding" : null,
      "qualifiedFinancialProduct" : null
    }, {
      "id" : 5072646397,
      "name" : "深圳市<em>中洛佳</em>尔科技有限公司",
      "type" : 1,
      "matchType" : "公司名称匹配",
      "base" : "广东",
      "legalPersonName" : "文真",
      "estiblishTime" : "2021-08-05 00:00:00.0",
      "regCapital" : "100万人民币",
      "regStatus" : "存续",
      "score" : "58",
      "orginalScore" : "5839",
      "bonusScore" : "0",
      "companyScore" : "58",
      "historyNames" : "",
      "categoryCode" : "659",
      "industry" : null,
      "humanNames" : "余熙锟\t:#0\t;\t文真\t:#0\t;\t文真\t:#1\t;\t",
      "trademarks" : null,
      "tmList" : null,
      "productList" : null,
      "usedBondName" : null,
      "bondName" : null,
      "bondNum" : null,
      "bondType" : null,
      "newtestName" : null,
      "regNumber" : "440300214517783",
      "orgNumber" : "MA5GXE0K-2",
      "creditCode" : "91440300MA5GXE0K29",
      "businessScope" : "移动通信设备销售;通讯设备销售;电子产品销售;家用电器销售;音响设备销售;电子元器件批发;电子元器件零售;钟表与计时仪器销售;日用百货销售;汽车零配件零售;汽车装饰用品销售;网络技术服务;信息技术咨询服务;技术服务;技术开发;技术咨询;技术交流;技术转让;技术推广;互联网销售;凭营业执照依法自主开展经营活动",
      "regLocation" : "深圳市龙岗区平湖街道辅城坳社区工业大道101号403A",
      "phone" : "13538040970\t;\t14775045553",
      "phoneList" : [ "13538040970", "14775045553" ],
      "phoneInfoList" : [ {
        "number" : "13538040970",
        "type" : "1",
        "label" : "1",
        "source" : null,
        "comment" : "号码可正常联系"
      }, {
        "number" : "14775045553",
        "type" : "9",
        "label" : "1",
        "source" : null,
        "comment" : "固定电话或非大陆号码"
      } ],
      "businessItemList" : null,
      "phoneNum" : "13538040970",
      "logo" : "",
      "city" : "深圳市",
      "district" : "龙岗区",
      "emails" : "13538040970@139.com\t;\t14775045553@139.com",
      "emailList" : [ "13538040970@139.com", "14775045553@139.com" ],
      "websites" : "",
      "hiddenPhones" : null,
      "abbr" : "",
      "tagList" : null,
      "companyType" : 1,
      "companyOrgType" : "有限责任公司\t;\t有限责任公司(自然人独资)",
      "labelList" : null,
      "matchField" : null,
      "latitude" : null,
      "longitude" : null,
      "legalPersonId" : "1953263390",
      "legalPersonType" : "1",
      "distance" : null,
      "categoryStr" : "软件和信息技术服务业",
      "isClaimed" : 0,
      "claimPkgType" : null,
      "realClaimPkgType" : null,
      "baiduUrl" : null,
      "isBranch" : 0,
      "alias" : "中洛佳尔",
      "claimInfo" : null,
      "hidden" : 0,
      "legalPersonShowStr" : "法定代表人",
      "regCapitalShowStr" : "注册资本",
      "estiblishTimeShowStr" : "成立日期",
      "multiMatchField" : [ ],
      "labelListV2" : [ "小微企业" ],
      "labelJsonList" : [ "{\"type\":1,\"value\":\"小微企业\"}" ],
      "taxCode" : "91440300MA5GXE0K29",
      "socialSecurityStaff_num" : null,
      "categoryCodeStd" : "517",
      "hasMorePhone" : null,
      "hasVideo" : null,
      "videoId" : null,
      "isRecommend" : null,
      "englishName" : "Shenzhen Zhongluo Jiaer Technology Co., Ltd",
      "firstPositionShowStr" : "法定代表人",
      "secondPositionShowStr" : "注册资本",
      "firstPositionValue" : "文真",
      "secondPositionValue" : "100万人民币",
      "bizType" : "7",
      "docFeature" : "{\"isFollowed\":0,\"isMonitored\":0,\"historyClicks\":0,\"byAnn\":0,\"timeClicks\":[],\"byBaidu\":0}",
      "companyNum" : null,
      "department" : "",
      "illegalType" : "0",
      "targetGid" : "",
      "targetName" : "",
      "changeTime" : "",
      "isIn" : "",
      "mainId" : "",
      "targetRegCapitalAmount" : "",
      "targetRegCapitalCurrency" : "",
      "legalPerson" : "",
      "gidForB" : "5072646397",
      "geoLocation" : null,
      "websiteFilingCount" : 0,
      "repCurrency" : null,
      "province" : "00440307\t;\t00440300\t;\t00440000",
      "areaCodes" : [ "00440307", "00440300", "00440000" ],
      "address" : null,
      "establishmentTime" : "20210805",
      "icps" : null,
      "icp" : "",
      "changeRatio" : "",
      "afterRatio" : "",
      "changeAmt" : "",
      "registerInstitute" : "深圳市市场监督管理局",
      "companyScale" : "小型",
      "abstractsBaseInfo" : "深圳市中洛佳尔科技有限公司，成立于2021年，位于广东省深圳市，是一家以从事软件和信息技术服务业为主的企业。企业注册资本100万人民币，超过了55%的广东省同行。",
      "financingRound" : "未融资",
      "staffNumReportYear" : 2022,
      "categoryCode2017List" : [ "I", "65", "659", "6599" ],
      "institutionTypeList" : [ "企业", "有限责任公司", "一人有限责任公司" ],
      "companyBrandInfo" : null,
      "companyGroupInfo" : null,
      "contantMap" : {
        "recallSrc" : "ES",
        "param_reg_capital" : "100.0",
        "establish_time_long" : "1628092800000"
      },
      "companyPhoneBook" : {
        "type" : null,
        "friendName" : null
      },
      "companyQuestions" : {
        "logos" : null,
        "participantCount" : null,
        "textContent" : null,
        "qid" : null
      },
      "executive" : null,
      "noActualCapital" : null,
      "threeMonthsLawsuit" : null,
      "residentialBuilding" : null,
      "qualifiedFinancialProduct" : null
    } ],
    "companyTotalPage" : 1,
    "companyTotal" : 4,
    "companyTotalStr" : "4",
    "adviceQuery" : null,
    "searchContent" : "中洛佳"
  }
} 
        """.trimIndent()
//        val parseObject = responseBody.parseObject<site.addzero.network.call.tianyancha.domain.search.JsonRootBean>()
        val parseObject = responseBody.parseObject<SearchRes>()

//        val searches = parseObject.data?.companyList?.filterNotNull()?.map { it.toSearch() } ?: emptyList()
        val searches = parseObject.data
        println(searches)


    }

}
