/**
 * Copyright 2019 bejson.com
 */
package site.addzero.network.call.tianyancha.domain.search


data class CompanyList(
    var id: Long = 0,
    var name: String? = null,
    var type: Int = 0,
    var matchType: String? = null,
    var base: String? = null,
    var legalPersonName: String? = null,
    var estiblishTime: String? = null,
    var regCapital: String? = null,
    var regStatus: String? = null,
    var score: String? = null,
    var orginalScore: String? = null,
    var bonusScore: String? = null,
    var companyScore: String? = null,
    var historyNames: String? = null,
    var categoryCode: String? = null,
    var industry: String? = null,
    var humanNames: String? = null,
    var trademarks: String? = null,
    var tmList: String? = null,
    var productList: String? = null,
    var usedBondName: String? = null,
    var bondName: String? = null,
    var bondNum: String? = null,
    var bondType: String? = null,
    var newtestName: String? = null,
    var regNumber: String? = null,
    var orgNumber: String? = null,
    var creditCode: String? = null,
    var businessScope: String? = null,
    var regLocation: String? = null,
    var phone: String? = null,
    var phoneList: MutableList<String?>? = null,
    var phoneNum: String? = null,
    var logo: String? = null,
    var city: String? = null,
    var district: String? = null,
    var emails: String? = null,
    var emailList: MutableList<String?>? = null,
    var websites: String? = null,
    var hiddenPhones: String? = null,
    var abbr: String? = null,
    var tagList: MutableList<String?>? = null,
    var companyType: Int = 0,
    var companyOrgType: String? = null,
    var labelList: MutableList<String?>? = null,
    var matchField: MatchField? = null,
    var latitude: Double = 0.0,
    var longitude: Double = 0.0,
    var legalPersonId: String? = null,
    var legalPersonType: String? = null,
    var distance: String? = null,
    var categoryStr: String? = null,
    var isClaimed: Int = 0,
    var claimPkgType: String? = null,
    var baiduUrl: String? = null,
    var isBranch: Int = 0,
    var alias: String? = null,
    var claimInfo: String? = null,
    var hidden: Int = 0,
    var legalPersonShowStr: String? = null,
    var regCapitalShowStr: String? = null,
    var estiblishTimeShowStr: String? = null,
    var contantMap: String? = null
)
