package site.addzero.apt.dict.processor.generator

import site.addzero.util.lsi.field.LsiField

/**
 * 字典类辅助IoC上下文生成器
 * 生成全局的类映射关系管理器
 */
object DictClassHelperIocContextGenerator {

    /**
     * 生成DictClassHelperIocContext类
     *
     * @param packageName 包名
     * @param processedClasses 所有处理过的类信息
     * @return 生成的Java代码
     */
    fun generateIocContext(packageName: String, processedClasses: List<ProcessedClassInfo>): String {
        return """
package $packageName;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import site.addzero.dict.trans.inter.LsiDictConvertor;

/**
 * 字典类辅助IoC上下文
 * 管理所有生成的字典类的映射关系
 * Auto-generated by DictTranslateProcessor
 */
public class DictClassHelperIocContext {
    
    // 单例实例
    private static final DictClassHelperIocContext INSTANCE = new DictClassHelperIocContext();
    
    // 类映射表：原始类 -> DTO类
    private final Map<Class<?>, Class<?>> classToDtoMap = new ConcurrentHashMap<>();
    
    // 导包映射表：类名 -> 全限定名
    private final Map<String, String> classNameToPackageMap = new ConcurrentHashMap<>();
    
    // 转换器映射表：原始类 -> 转换器实例
    private final Map<Class<?>, LsiDictConvertor<?, ?>> convertorMap = new ConcurrentHashMap<>();
    
    private DictClassHelperIocContext() {
        initializeMappings();
    }
    
    public static DictClassHelperIocContext getInstance() {
        return INSTANCE;
    }
    
    /**
     * 初始化所有映射关系
     */
    private void initializeMappings() {
        ${generateMappingInitialization(processedClasses)}
    }
    
    /**
     * 获取原始类对应的DTO类
     */
    @SuppressWarnings("unchecked")
    public <T, D> Class<D> getDtoClass(Class<T> originalClass) {
        return (Class<D>) classToDtoMap.get(originalClass);
    }
    
    /**
     * 获取类的全限定名
     */
    public String getFullClassName(String simpleName) {
        return classNameToPackageMap.get(simpleName);
    }
    
    /**
     * 获取转换器实例
     */
    @SuppressWarnings("unchecked")
    public <T, D> LsiDictConvertor<T, D> getConvertor(Class<T> originalClass) {
        return (LsiDictConvertor<T, D>) convertorMap.get(originalClass);
    }
    
    /**
     * 注册转换器实例
     */
    public <T, D> void registerConvertor(Class<T> originalClass, LsiDictConvertor<T, D> convertor) {
        convertorMap.put(originalClass, convertor);
    }
    
    ${generateUtilityMethods(processedClasses)}
}
        """.trimIndent()
    }

    private fun generateMappingInitialization(processedClasses: List<ProcessedClassInfo>): String {
        return processedClasses.joinToString("\n        ") { classInfo ->
            """
        // Mappings for ${classInfo.originalClassName}
        try {
            Class<?> originalClass = Class.forName("${classInfo.originalFullName}");
            Class<?> dtoClass = Class.forName("${classInfo.dtoFullName}");
            classToDtoMap.put(originalClass, dtoClass);
            classNameToPackageMap.put("${classInfo.originalClassName}", "${classInfo.originalFullName}");
            classNameToPackageMap.put("${classInfo.dtoClassName}", "${classInfo.dtoFullName}");
        } catch (ClassNotFoundException e) {
            // Log warning but continue
            System.err.println("Warning: Could not load classes for ${classInfo.originalClassName}: " + e.getMessage());
        }
            """.trimIndent()
        }
    }

    private fun generateUtilityMethods(processedClasses: List<ProcessedClassInfo>): String {
        return """
    /**
     * 检查是否有对应的DTO类
     */
    public boolean hasDtoClass(Class<?> originalClass) {
        return classToDtoMap.containsKey(originalClass);
    }
    
    /**
     * 获取所有已注册的原始类
     */
    public Set<Class<?>> getAllOriginalClasses() {
        return new HashSet<>(classToDtoMap.keySet());
    }
    
    /**
     * 获取所有已注册的DTO类
     */
    public Set<Class<?>> getAllDtoClasses() {
        return new HashSet<>(classToDtoMap.values());
    }
        """.trimIndent()
    }
}

/**
 * 处理过的类信息
 */
data class ProcessedClassInfo(
    val originalClassName: String,
    val originalFullName: String,
    val dtoClassName: String,
    val dtoFullName: String,
    val convertorClassName: String,
    val convertorFullName: String,
    val dictFields: List<LsiField>
)
