package site.addzero.apt.dict.processor.generator

import site.addzero.util.lsi.field.LsiField

/**
 * 字典类辅助IoC上下文生成器
 * 生成全局的类映射关系管理器
 */
object DictClassHelperIocContextGenerator {

    /**
     * 生成DictClassHelperIocContext类
     *
     * @param packageName 包名
     * @param processedClasses 所有处理过的类信息
     * @return 生成的Java代码
     */
    fun generateIocContext(packageName: String, processedClasses: List<ProcessedClassInfo>): String {
        return """
package $packageName;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import site.addzero.dict.trans.inter.LsiDictConvertor;
import site.addzero.dict.trans.inter.DictTranslationFactory;

/**
 * 字典类辅助IoC上下文 - 完全无反射版本
 * 使用编译时生成的表达式和工厂方法
 * Auto-generated by DictTranslateProcessor
 */
public class DictClassHelperIocContext {
    
    // 单例实例
    private static final DictClassHelperIocContext INSTANCE = new DictClassHelperIocContext();
    
    // 类名映射表：类名 -> 全限定名（编译时确定）
    private final Map<String, String> classNameToPackageMap = new ConcurrentHashMap<>();
    
    // 转换器工厂映射：类名 -> 转换器工厂函数（编译时生成）
    private final Map<String, Function<Object, Object>> convertorFactoryMap = new ConcurrentHashMap<>();
    
    // DTO工厂映射：类名 -> DTO工厂函数（编译时生成）
    private final Map<String, Function<Object, Object>> dtoFactoryMap = new ConcurrentHashMap<>();
    
    private DictClassHelperIocContext() {
        initializeMappings();
        initializeFactories();
    }
    
    public static DictClassHelperIocContext getInstance() {
        return INSTANCE;
    }
    
    /**
     * 初始化所有映射关系
     */
    private void initializeMappings() {
        ${generateMappingInitialization(processedClasses)}
    }
    
    /**
     * 初始化工厂方法（编译时生成，无反射）
     */
    private void initializeFactories() {
        ${generateFactoryInitialization(processedClasses)}
    }
    
    /**
     * 获取类的全限定名
     */
    public String getFullClassName(String simpleName) {
        return classNameToPackageMap.get(simpleName);
    }
    
    /**
     * 创建DTO实例（使用编译时生成的工厂方法）
     */
    @SuppressWarnings("unchecked")
    public <T, D> D createDto(String className, T originalEntity) {
        Function<Object, Object> factory = dtoFactoryMap.get(className);
        if (factory != null) {
            return (D) factory.apply(originalEntity);
        }
        return null;
    }
    
    /**
     * 创建转换器实例（使用编译时生成的工厂方法）
     */
    @SuppressWarnings("unchecked")
    public <T, D> LsiDictConvertor<T, D> createConvertor(String className, Object sqlExecutor) {
        Function<Object, Object> factory = convertorFactoryMap.get(className);
        if (factory != null) {
            return (LsiDictConvertor<T, D>) factory.apply(sqlExecutor);
        }
        return null;
    }
    
    /**
     * 执行字典翻译（使用单例工厂）
     */
    public <T, D> D translateEntity(String className, T entity) {
        // 使用编译时生成的转换逻辑
        D dto = createDto(className, entity);
        if (dto != null) {
            // 通过单例工厂执行翻译
            return dto; // 翻译逻辑在DTO构造时已执行
        }
        return null;
    }
    
    ${generateUtilityMethods(processedClasses)}
}
        """.trimIndent()
    }

    private fun generateMappingInitialization(processedClasses: List<ProcessedClassInfo>): String {
        return processedClasses.joinToString("\n        ") { classInfo ->
            """
        // Expression-based mappings for ${classInfo.originalClassName} (NO REFLECTION)
        // Direct class references - compiled at build time
        classNameToPackageMap.put("${classInfo.originalClassName}", "${classInfo.originalFullName}");
        classNameToPackageMap.put("${classInfo.dtoClassName}", "${classInfo.dtoFullName}");
        classNameToPackageMap.put("${classInfo.convertorClassName}", "${classInfo.convertorFullName}");
            """.trimIndent()
        }
    }

    private fun generateFactoryInitialization(processedClasses: List<ProcessedClassInfo>): String {
        return processedClasses.joinToString("\n        ") { classInfo ->
            """
        // Factory methods for ${classInfo.originalClassName} (NO REFLECTION)
        dtoFactoryMap.put("${classInfo.originalClassName}", entity -> {
            if (entity instanceof ${classInfo.originalFullName}) {
                return new ${classInfo.dtoFullName}((${classInfo.originalFullName}) entity);
            }
            return null;
        });
        
        convertorFactoryMap.put("${classInfo.originalClassName}", sqlExecutor -> {
            if (sqlExecutor instanceof site.addzero.dict.trans.inter.SqlExecutor) {
                return new ${classInfo.convertorFullName}((site.addzero.dict.trans.inter.SqlExecutor) sqlExecutor);
            }
            return null;
        });
            """.trimIndent()
        }
    }

    private fun generateUtilityMethods(processedClasses: List<ProcessedClassInfo>): String {
        return """
    /**
     * 检查是否有对应的DTO工厂
     */
    public boolean hasDtoFactory(String className) {
        return dtoFactoryMap.containsKey(className);
    }
    
    /**
     * 检查是否有对应的转换器工厂
     */
    public boolean hasConvertorFactory(String className) {
        return convertorFactoryMap.containsKey(className);
    }
    
    /**
     * 获取所有已注册的类名
     */
    public Set<String> getAllRegisteredClassNames() {
        return new HashSet<>(classNameToPackageMap.keySet());
    }
    
    /**
     * 获取缓存统计信息
     */
    public Object getCacheStats() {
        return DictTranslationFactory.getCacheStats();
    }
    
    /**
     * 清理所有缓存
     */
    public void clearCaches() {
        DictTranslationFactory.clearCaches();
    }
        """.trimIndent()
    }
}

/**
 * 处理过的类信息
 */
data class ProcessedClassInfo(
    val originalClassName: String,
    val originalFullName: String,
    val dtoClassName: String,
    val dtoFullName: String,
    val convertorClassName: String,
    val convertorFullName: String,
    val dictFields: List<LsiField>
)
