package site.addzero.apt.dict.processor.generator

import site.addzero.util.lsi.clazz.LsiClass
import site.addzero.util.lsi.field.LsiField

/**
 * 字典转换器生成器
 * 生成实现LsiDictConvertor接口的转换器类
 */
object DictConvertorGenerator {
    
    /**
     * 生成字典转换器类
     * 
     * @param packageName 包名
     * @param originalClass 原始实体类
     * @param dictFields 包含@Dict注解的字段
     * @return 生成的Java代码
     */
    fun generateConvertor(packageName: String, originalClass: LsiClass, dictFields: List<LsiField>): String {
        val originalClassName = originalClass.name ?: "Unknown"
        val dtoClassName = "${originalClassName}DictDTO"
        val convertorClassName = "${originalClassName}Convertor"
        
        return """
package $packageName;

import site.addzero.dict.trans.inter.LsiDictConvertor;
import java.util.*;

/**
 * Dictionary convertor for ${originalClassName}
 * Generated by DictTranslateProcessor
 * 
 * Implements LsiDictConvertor interface for bidirectional translation
 */
public class $convertorClassName implements LsiDictConvertor<$originalClassName, $dtoClassName> {
    
    public $convertorClassName() {
        // Constructor
    }
    
    @Override
    public $dtoClassName code2name($originalClassName entity) {
        if (entity == null) {
            return null;
        }
        
        // Create DTO from original entity using static method
        $dtoClassName dto = $dtoClassName.fromOriginal(entity);
        
        // Perform dictionary translation
        performDictTranslation(dto);
        
        return dto;
    }
    
    @Override
    public $originalClassName name2code($dtoClassName dto) {
        if (dto == null) {
            return null;
        }
        
        // Convert DTO back to original entity
        return dto.toOriginal();
    }
    
    /**
     * Batch code2name translation for multiple entities
     */
    public List<$dtoClassName> code2name(List<$originalClassName> entities) {
        if (entities == null || entities.isEmpty()) {
            return new ArrayList<>();
        }
        
        List<$dtoClassName> dtos = new ArrayList<>();
        for ($originalClassName entity : entities) {
            dtos.add(code2name(entity));
        }
        
        return dtos;
    }
    
    /**
     * Batch name2code translation for multiple DTOs
     */
    public List<$originalClassName> name2code(List<$dtoClassName> dtos) {
        if (dtos == null || dtos.isEmpty()) {
            return new ArrayList<>();
        }
        
        List<$originalClassName> entities = new ArrayList<>();
        for ($dtoClassName dto : dtos) {
            entities.add(name2code(dto));
        }
        
        return entities;
    }
    
    /**
     * Perform dictionary translation on DTO
     */
    private void performDictTranslation($dtoClassName dto) {
        if (dto == null) return;
        
        ${generateDictTranslationLogic(dictFields)}
    }
    
    ${generateUtilityMethods(originalClassName, dtoClassName)}
}
        """.trimIndent()
    }
    
    /**
     * 生成字典翻译逻辑
     */
    private fun generateDictTranslationLogic(dictFields: List<LsiField>): String {
        if (dictFields.isEmpty()) {
            return "// No dictionary fields to translate"
        }
        
        val systemDictFields = dictFields.filter { field ->
            val dictAnnotation = field.annotations.find { it.simpleName == "Dict" }
            val dicCode = dictAnnotation?.getAttribute("dicCode") as? String
            dicCode != null && dicCode.isNotEmpty()
        }
        
        val tableDictFields = dictFields.filter { field ->
            val dictAnnotation = field.annotations.find { it.simpleName == "Dict" }
            val tab = dictAnnotation?.getAttribute("tab") as? String
            tab != null && tab.isNotEmpty()
        }
        
        val systemDictLogic = if (systemDictFields.isNotEmpty()) {
            generateSystemDictTranslation(systemDictFields)
        } else ""
        
        val tableDictLogic = if (tableDictFields.isNotEmpty()) {
            generateTableDictTranslation(tableDictFields)
        } else ""
        
        return """
        // System dictionary translation
        $systemDictLogic
        
        // Table dictionary translation
        $tableDictLogic
        """.trimIndent()
    }
    
    /**
     * 生成系统字典翻译逻辑
     */
    private fun generateSystemDictTranslation(systemDictFields: List<LsiField>): String {
        return systemDictFields.joinToString("\n        ") { field ->
            val fieldName = field.name ?: "unknown"
            val dictAnnotation = field.annotations.find { it.simpleName == "Dict" }
            val dicCode = dictAnnotation?.getAttribute("dicCode") as? String ?: ""
            val translationFieldName = getTranslationFieldName(field)
            
            """
        // Translate system dict field: $fieldName
        if (dto.get${fieldName.replaceFirstChar { it.uppercase() }}() != null) {
            // TODO: Implement system dictionary translation for dicCode: $dicCode
            // String translatedValue = systemDictService.translate("$dicCode", dto.get${fieldName.replaceFirstChar { it.uppercase() }}().toString());
            // dto.set${translationFieldName.replaceFirstChar { it.uppercase() }}(translatedValue);
        }
            """.trimIndent()
        }
    }
    
    /**
     * 生成表字典翻译逻辑
     */
    private fun generateTableDictTranslation(tableDictFields: List<LsiField>): String {
        return tableDictFields.joinToString("\n        ") { field ->
            val fieldName = field.name ?: "unknown"
            val dictAnnotation = field.annotations.find { it.simpleName == "Dict" }
            val tab = dictAnnotation?.getAttribute("tab") as? String ?: ""
            val codeColumn = dictAnnotation?.getAttribute("codeColumn") as? String ?: "id"
            val nameColumn = dictAnnotation?.getAttribute("nameColumn") as? String ?: "name"
            val translationFieldName = getTranslationFieldName(field)
            
            """
        // Translate table dict field: $fieldName
        if (dto.get${fieldName.replaceFirstChar { it.uppercase() }}() != null) {
            // TODO: Implement table dictionary translation for table: $tab
            // String translatedValue = tableDictService.translate("$tab", "$codeColumn", "$nameColumn", dto.get${fieldName.replaceFirstChar { it.uppercase() }}().toString());
            // dto.set${translationFieldName.replaceFirstChar { it.uppercase() }}(translatedValue);
        }
            """.trimIndent()
        }
    }
    
    /**
     * 获取翻译字段名
     */
    private fun getTranslationFieldName(field: LsiField): String {
        val dictAnnotation = field.annotations.find { it.simpleName == "Dict" }
        val serializationAlias = dictAnnotation?.getAttribute("serializationAlias") as? String
        val nameColumn = dictAnnotation?.getAttribute("nameColumn") as? String
        val fieldName = field.name ?: "unknown"
        
        return when {
            !serializationAlias.isNullOrEmpty() -> serializationAlias
            !nameColumn.isNullOrEmpty() -> nameColumn
            else -> "${fieldName}Text"
        }
    }
    
    /**
     * 生成工具方法
     */
    private fun generateUtilityMethods(originalClassName: String, dtoClassName: String): String {
        return """
    /**
     * Check if entity has dictionary fields that need translation
     */
    public boolean needsTranslation($originalClassName entity) {
        return entity != null;
    }
    
    /**
     * Check if DTO has been translated
     */
    public boolean isTranslated($dtoClassName dto) {
        return dto != null;
    }
        """.trimIndent()
    }
}