package site.addzero.network.call.tianyancha.entity

data class Data(
    val abInfo: List<AbInfo>,
    val actualCapital: String,
    val addressList: List<Address>,
    val alias: String,
    val approvedTime: Long,
    val base: String,
    val baseInfo: String,
    val branchSocialStaffNum: String,
    val businessScope: String,
    val businessStatusInfo: Any? = null,
    val companyAssets: Any? = null,
    val companyBizOrgType: String,
    val companyBizType: Int,
    val companyCreditCode: String,
    val companyOrgType: String,
    val companyProfilePlainText: String,
    val companyProfilePlainText4Copy: String,
    val companyProfileRichText: List<CompanyProfileRichText>,
    val companyShowBizTypeName: String,
    val companyTimeExplain: String,
    val companyTimeTitle: String,
    val companyType: Int,
    val complexName: String,
    val creditCode: String,
    val email: String,
    val emailDetailList: List<EmailDetail>,
    val emailList: List<String>,
    val enNameSource: String,
    val enterpriseScaleInfo: EnterpriseScaleInfo,
    val entityType: Int,
    val equityUrl: String,
    val estiblishTime: Long,
    val estiblishTimeTitleName: String,
    val extraInfo: Any? = null,
    val fromTime: Long,
    val id: Long,
    val industry: Any? = null,
    val industry2017: String,
    val industryChainList: List<IndustryChain>,
    val industryInfo: IndustryInfo,
    val industryNationalStdLv3Code: String,
    val isBranch: Boolean,
    val isClaimed: Int,
    val legalInfo: LegalInfo,
    val legalPersonId: Long,
    val legalPersonName: String,
    val legalPersonPid: String,
    val legalPersonType: Int,
    val legalTitleName: String,
    val link: Int,
    val listedPlateList: List<Any>,
    val listedStatusType: Int,
    val listedStatusTypeForSenior: Int,
    val logo: String,
    val name: String,
    val newCompanyIncome: Any? = null,
    val newCompanyProfit: Any? = null,
    val operatingIncomeInfo: Any? = null,
    val operatingProfitInfo: Any? = null,
    val orgNumber: String,
    val orgTypeName: String,
    val originalPercentileScore: Int,
    val parentId: Any? = null,
    val percentileScore: Int,
    val phoneList: List<String>,
    val phoneNumber: String,
    val phoneSourceList: List<PhoneSource>,
    val property3: String,
    val regCapital: String,
    val regCapitalAmount: String,
    val regCapitalAmountUnit: String,
    val regCapitalAmt: Int,
    val regCapitalCurrency: String,
    val regCapitalLabel: String,
    val regInstitute: String,
    val regLocation: String,
    val regLocationTitle: String,
    val regNumber: String,
    val regStatus: String,
    val regTitleName: String,
    val relatedIndustryChainCount: Int,
    val safetype: String,
    val scienceTechnologyInfo: ScienceTechnologyInfo,
    val sensitiveEntityType: Int,
    val shortname: String,
    val showBranchTrendChart: Boolean,
    val showCapitalReductionNoticeCount: Boolean,
    val showTrendChart: Boolean,
    val socialStaffNum: String,
    val staffNumInfo: StaffNumInfo,
    val staffNumInfoList: StaffNumInfoList,
    val staffNumInfoListThreeYear: List<StaffNumInfoThreeYear>,
    val staffNumRange: String,
    val tagList: List<Tag>,
    val tagListV2: List<TagV2>,
    val tagListV3: List<TagV3>,
    val tags: String,
    val taxAddress: String,
    val taxNumber: String,
    val taxPhone: String,
    val taxQualification: String,
    val type: Int,
    val updateTime4Index: Long,
    val updateTimes: Long,
    val updatetime: Long,
    val websiteList: Any? = null,
    val wechatCount: Int,
    val year4BranchSocialStaffNum: Int,
    val year4SocialStaffNum: Int
)