package site.addzero.apt.dict.template

/**
 * Simple Template Manager for code generation
 * 
 * Manages string template rendering for enhanced entity generation
 * (Simplified version without JTE dependency for Java 11 compatibility)
 */
class JTETemplateManager {
    
    /**
     * Renders enhanced entity Java code using string templates
     */
    fun renderEnhancedEntity(
        className: String,
        packageName: String,
        fields: List<Map<String, Any>>,
        imports: List<String> = emptyList()
    ): String {
        val importsSection = if (imports.isNotEmpty()) {
            imports.joinToString("\n") { "import $it;" }
        } else {
            ""
        }
        
        val fieldsSection = fields.joinToString("\n") { field ->
            val fieldName = field["name"] as String
            val fieldType = field["type"] as String
            "    private $fieldType $fieldName;"
        }
        
        val gettersSetters = fields.joinToString("\n\n") { field ->
            val fieldName = field["name"] as String
            val fieldType = field["type"] as String
            val capitalizedName = fieldName.replaceFirstChar { it.uppercase() }
            
            """    public $fieldType get$capitalizedName() {
        return $fieldName;
    }
    
    public void set$capitalizedName($fieldType $fieldName) {
        this.$fieldName = $fieldName;
    }"""
        }
        
        return """package $packageName;

$importsSection

/**
 * Enhanced entity class generated by APT processor
 */
public class $className {
$fieldsSection

$gettersSetters

    /**
     * Translate dictionary fields using TransApi
     */
    public void translate(Object transApi) {
        // Translation logic will be generated here
    }
}"""
    }
    
    /**
     * Renders translation metadata Java code
     */
    fun renderTranslationMetadata(
        className: String,
        packageName: String,
        entityClass: String,
        dictFields: List<Map<String, Any>>
    ): String {
        return """package $packageName;

/**
 * Translation metadata for $entityClass
 */
public class $className {
    // Metadata implementation will be generated here
}"""
    }
}