/**
 * Copyright 2019 bejson.com
 */
package site.addzero.network.call.tianyancha.domain.baseinfo


data class Data(
    val isBranch: Int = 0,
    val updatetime: Long = 0,
    val staffNumRange: String? = null,
    val phoneList: MutableList<String?>? = null,
    val portray: String? = null,
    val round: String? = null,
    val fromTime: Long = 0,
    val type: Int = 0,
    val entityType: Int = 0,
    val isHightTech: String? = null,
    val percentileScore: Int = 0,
    val haveReport: Boolean = false,
    val phoneNumber: String? = null,
    val regInstitute: String? = null,
    val regLocation: String? = null,
    val industry: String? = null,
    val baiduAuthURLWAP: String? = null,
    val inverstStatus: String? = null,
    val orgApprovedInstitute: String? = null,
    val businessScope: String? = null,
    val equityUrl: String? = null,
    val property4: String? = null,
    val property3: String? = null,
    val orgNumber: String? = null,
    val estiblishTime: Long = 0,
    val regStatus: String? = null,
    val legalPersonName: String? = null,
    val legalTitleName: String? = null,
    val baiduAuthURLWWW: String? = null,
    val ownId: String? = null,
    val legalPersonId: Long = 0,
    val sourceFlag: String? = null,
    val isClaimed: Int = 0,
    val actualCapital: String? = null,
    val websiteList: String? = null,
    val flag: Int = 0,
    val correctCompanyId: String? = null,
    val email: String? = null,
    val updateTimes: Long = 0,
    val creditCode: String? = null,
    val estiblishTimeTitleName: String? = null,
    val weibo: String? = null,
    val link: Int = 0,
    val categoryScore: Int = 0,
    val id: Long = 0,
    val isMicroEnt: Int = 0,
    val regNumber: String? = null,
    val regCapital: String? = null,
    val name: String? = null,
    val safetype: String? = null,
    val approvedTime: Long = 0,
    val regTitleName: String? = null,
    val socialStaffNum: Int = 0,
    val tags: String? = null,
    val logo: String? = null,
    val taxNumber: String? = null,
    val alias: String? = null,
    val legalInfo: LegalInfo? = null,
    val baseInfo: String? = null,
    val toTime: Long = 0,
    val companyOrgType: String? = null,
    val base: String? = null,
    val companyType: Int = 0,
    val companyId: Int = 0,
    val tagList: MutableList<TagList?>? = null
)