package site.addzero.apt.dict.example

import site.addzero.apt.dict.annotations.DictField
import site.addzero.apt.dict.annotations.DictTranslate

/**
 * Example demonstrating APT processor usage
 * 
 * This example shows how to use @DictTranslate and @DictField annotations
 * to generate enhanced entity classes at compile time.
 */

/**
 * Simple user entity with dictionary translation annotations
 */
@DictTranslate(suffix = "Enhanced")
data class SimpleUserEntity(
    val id: Long,
    val username: String,
    
    @DictField(dictCode = "user_status", targetField = "statusText")
    val status: String,
    
    @DictField(
        table = "sys_department", 
        codeColumn = "id", 
        nameColumn = "dept_name", 
        targetField = "departmentText"
    )
    val departmentId: Long
)

/**
 * Complex RBAC entity with multiple dictionary fields
 */
@DictTranslate(suffix = "Enhanced", generateExtensions = true)
data class RoleEntity(
    val id: Long,
    val roleName: String,
    
    @DictField(dictCode = "role_status", targetField = "statusText")
    val status: String,
    
    @DictField(
        table = "sys_organization",
        codeColumn = "org_code",
        nameColumn = "org_name",
        targetField = "organizationText",
        condition = "status = 1 AND level <= 3"
    )
    val organizationCode: String,
    
    @DictField(
        table = "sys_permission",
        codeColumn = "perm_code",
        nameColumn = "perm_name",
        targetField = "permissionText"
    )
    val permissionCode: String
)

/**
 * Nested entity with multiple dictionary types
 */
@DictTranslate(suffix = "Enhanced")
data class OrderEntity(
    val id: Long,
    val orderNo: String,
    
    @DictField(dictCode = "order_status", targetField = "statusText")
    val status: String,
    
    @DictField(dictCode = "payment_method", targetField = "paymentMethodText")
    val paymentMethod: String,
    
    @DictField(
        table = "sys_customer",
        codeColumn = "customer_id",
        nameColumn = "customer_name",
        targetField = "customerText"
    )
    val customerId: Long,
    
    @DictField(
        table = "sys_region",
        codeColumn = "region_code",
        nameColumn = "region_name",
        targetField = "regionText",
        condition = "status = 'ACTIVE' AND country_code = 'CN'"
    )
    val regionCode: String
)

/**
 * Example usage of generated enhanced entities
 */
class APTProcessorUsageExample {
    
    fun demonstrateEnhancedEntityUsage() {
        // Original entity
        val user = SimpleUserEntity(
            id = 1L,
            username = "john_doe",
            status = "ACTIVE",
            departmentId = 100L
        )
        
        // This would be generated by APT processor:
        // UserEntityEnhanced class with:
        // - statusText: String? field
        // - departmentText: String? field
        // - translate(transApi: TransApi, sourceEntity: SimpleUserEntity) method
        // - translateAsync(transApi: TransApi, sourceEntity: SimpleUserEntity) method
        // - populateFromContext(context: Map<String, Any?>) method
        
        println("Original user: $user")
        println("Enhanced entity would be generated at compile time with translation fields")
    }
    
    fun demonstrateComplexEntityUsage() {
        val role = RoleEntity(
            id = 1L,
            roleName = "Administrator",
            status = "ACTIVE",
            organizationCode = "ORG001",
            permissionCode = "PERM_ADMIN"
        )
        
        // Generated RoleEntityEnhanced would have:
        // - statusText: String?
        // - organizationText: String?
        // - permissionText: String?
        // - All translation methods for batch processing
        
        println("Complex role entity: $role")
    }
}

/**
 * Expected generated Java code structure (for reference)
 */
object ExpectedGeneratedCode {
    
    val userEntityEnhancedExample = """
        package site.addzero.apt.dict.example;
        
        import site.addzero.apt.dict.service.TransApi;
        import site.addzero.apt.dict.service.DictModel;
        import java.util.*;
        import java.util.concurrent.CompletableFuture;
        
        /**
         * Enhanced version of UserEntity with compile-time dictionary translation support.
         * 
         * Generated by JavaEntityEnhancer at compile time from DSL configuration.
         */
        public class UserEntityEnhanced {
            
            private String statusText;
            private String departmentText;
            
            public UserEntityEnhanced() {
            }
            
            public String getStatusText() {
                return this.statusText;
            }
            
            public void setStatusText(String statusText) {
                this.statusText = statusText;
            }
            
            public String getDepartmentText() {
                return this.departmentText;
            }
            
            public void setDepartmentText(String departmentText) {
                this.departmentText = departmentText;
            }
            
            public void translate(TransApi transApi, UserEntity sourceEntity) {
                // System dictionary batch translation
                // Table dictionary batch translation
            }
            
            public CompletableFuture<Void> translateAsync(TransApi transApi, UserEntity sourceEntity) {
                return CompletableFuture.runAsync(() -> translate(transApi, sourceEntity));
            }
        }
    """.trimIndent()
}