package site.addzero.jimmer.apt.processor.model

import site.addzero.util.lsi.field.LsiField

/**
 * Jimmer字段元数据
 * 
 * 包含从Jimmer实体字段中提取的所有元数据信息
 */
data class FieldMetadata(
    /** LSI字段抽象 */
    val lsiField: LsiField,
    
    /** 列名 */
    val columnName: String,
    
    /** 是否为主键 */
    val isPrimaryKey: Boolean,
    
    /** 是否自动生成 */
    val isAutoGenerated: Boolean,
    
    /** 是否为业务键 */
    val isBusinessKey: Boolean,
    
    /** 是否为计算属性 */
    val isFormula: Boolean,
    
    /** 是否为IdView */
    val isIdView: Boolean,
    
    /** 是否为版本字段 */
    val isVersion: Boolean,
    
    /** 列类型 */
    val columnType: String,
    
    /** 是否可空 */
    val nullable: Boolean,
    
    /** 长度限制 */
    val length: Int,
    
    /** 精度 */
    val precision: Int,
    
    /** 小数位数 */
    val scale: Int,
    
    /** Jimmer特定的字段信息 */
    val jimmerFieldInfo: JimmerFieldInfo
)