package site.addzero.device.protocol.modbus.codegen

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import site.addzero.device.protocol.modbus.codegen.model.ModbusDocModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusFieldModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusOperationModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusPropertyModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnTypeModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusServiceModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusTransportKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusValueKind

class ModbusMetadataCoreTest {

    @Test
    fun shouldRoundTripMetadataJsonAndRenderPureContracts() {
        val services = listOf(sampleReadService(), sampleWriteService())

        val payload = ModbusMetadataJsonCodec.encodeServices(services)
        val decoded = ModbusMetadataJsonCodec.decodeServices(payload, transport = ModbusTransportKind.RTU)
        assertEquals(2, decoded.size)
        assertEquals("DeviceApi", decoded.first().interfaceSimpleName)

        val artifacts =
            ModbusKotlinContractGenerator.render(
                ModbusKotlinContractGenerationRequest(
                    services = decoded,
                    fileHeader = "Generated by test. DO NOT EDIT.",
                ),
            )
        val deviceApi = artifacts.first { artifact -> artifact.fileName == "DeviceApi" }.content
        val dto = artifacts.first { artifact -> artifact.fileName == "BoardSnapshotRegisters" }.content

        assertContains(deviceApi, "interface DeviceApi")
        assertContains(deviceApi, "suspend fun getBoardSnapshot(): BoardSnapshotRegisters")
        assertContains(dto, "data class BoardSnapshotRegisters(")
        assertContains(dto, "val uptimeMs: Int")
        assertContains(dto, "val deviceLabel: String")
    }

    private fun sampleReadService(): ModbusServiceModel =
        ModbusServiceModel(
            interfacePackage = "site.addzero.kcloud.plugins.mcuconsole.modbus.device",
            interfaceSimpleName = "DeviceApi",
            interfaceQualifiedName = "site.addzero.kcloud.plugins.mcuconsole.modbus.device.DeviceApi",
            serviceId = "device",
            summary = "设备读接口",
            basePath = "/api/modbus",
            transport = ModbusTransportKind.RTU,
            doc = ModbusDocModel(summary = "设备读接口"),
            operations =
                listOf(
                    ModbusOperationModel(
                        methodName = "getBoardSnapshot",
                        operationId = "get-board-snapshot",
                        functionCodeName = "READ_INPUT_REGISTERS",
                        address = 100,
                        quantity = 10,
                        requestClassName = "DeviceApiRtuGetBoardSnapshotRequest",
                        requestQualifiedName = "site.addzero.kcloud.plugins.mcuconsole.modbus.device.generated.DeviceApiRtuGetBoardSnapshotRequest",
                        parameters = emptyList(),
                        returnType =
                            ModbusReturnTypeModel(
                                qualifiedName = "site.addzero.kcloud.plugins.mcuconsole.modbus.device.BoardSnapshotRegisters",
                                simpleName = "BoardSnapshotRegisters",
                                kind = ModbusReturnKind.DTO,
                                docSummary = "板卡运行信息",
                                properties =
                                    listOf(
                                        ModbusPropertyModel(
                                            name = "uptimeMs",
                                            qualifiedType = "kotlin.Int",
                                            valueKind = ModbusValueKind.INT,
                                            field = ModbusFieldModel("U32_BE", 0, 0, 1, 2),
                                            doc = "运行时长",
                                        ),
                                        ModbusPropertyModel(
                                            name = "deviceLabel",
                                            qualifiedType = "kotlin.String",
                                            valueKind = ModbusValueKind.STRING,
                                            field = ModbusFieldModel("STRING_ASCII", 2, 0, 8, 8),
                                            doc = "设备标签",
                                        ),
                                    ),
                            ),
                        doc = ModbusDocModel(summary = "读取板卡运行信息"),
                    ),
                ),
        )

    private fun sampleWriteService(): ModbusServiceModel =
        ModbusServiceModel(
            interfacePackage = "site.addzero.kcloud.plugins.mcuconsole.modbus.device",
            interfaceSimpleName = "DeviceWriteApi",
            interfaceQualifiedName = "site.addzero.kcloud.plugins.mcuconsole.modbus.device.DeviceWriteApi",
            serviceId = "device-write",
            summary = "设备写接口",
            basePath = "/api/modbus",
            transport = ModbusTransportKind.RTU,
            doc = ModbusDocModel(summary = "设备写接口"),
            operations =
                listOf(
                    ModbusOperationModel(
                        methodName = "writeIndicatorLights",
                        operationId = "write-indicator-lights",
                        functionCodeName = "WRITE_MULTIPLE_COILS",
                        address = 0,
                        quantity = 2,
                        requestClassName = "DeviceWriteApiRtuWriteIndicatorLightsRequest",
                        requestQualifiedName = "site.addzero.kcloud.plugins.mcuconsole.modbus.device.generated.DeviceWriteApiRtuWriteIndicatorLightsRequest",
                        parameters = emptyList(),
                        returnType =
                            ModbusReturnTypeModel(
                                qualifiedName = "site.addzero.device.protocol.modbus.model.ModbusCommandResult",
                                simpleName = "ModbusCommandResult",
                                kind = ModbusReturnKind.COMMAND_RESULT,
                            ),
                        doc = ModbusDocModel(summary = "写入指示灯"),
                    ),
                ),
        )
}
