package site.addzero.ksp.serviceloader

/**
 * Annotation-based implementation of CodeGeneratorService
 */
class AnnotationCodeGenerator : CodeGeneratorService {
    override val name = "AnnotationGenerator"

    override fun generate(context: String): String {
        return """
            // Generated by AnnotationCodeGenerator
            @Target(AnnotationTarget.FUNCTION)
            annotation class Generated${context.capitalize()}()
        """.trimIndent()
    }

    override fun supports(context: String): Boolean {
        return context.startsWith("@")
    }
}