package site.addzero.ksp.serviceloader

/**
 * Default implementation of CodeGeneratorService
 */
class DefaultCodeGenerator : CodeGeneratorService {
    override val name = "DefaultGenerator"

    override fun generate(context: String): String {
        return """
            // Generated by DefaultCodeGenerator
            fun $context() {
                println("This is auto-generated code for $context")
            }
        """.trimIndent()
    }

    override fun supports(context: String): Boolean {
        return context.isNotEmpty()
    }
}