package site.addzero.ksp.serviceloader

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import java.util.ServiceLoader

/**
 * KSP Processor that demonstrates ServiceLoader usage during compilation
 */
class ServiceLoaderProcessor(
    private val environment: SymbolProcessorEnvironment
) : SymbolProcessor {

    private val codeGenerator = environment.codeGenerator
    private val logger = environment.logger

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // Log that processor is running
        logger.info("ServiceLoaderProcessor: Starting processing")

        // Try to load services using ServiceLoader
        try {
            val serviceLoader = ServiceLoader.load(CodeGeneratorService::class.java)
            val services = serviceLoader.iterator()

            logger.info("ServiceLoaderProcessor: Found CodeGeneratorService implementations:")

            val generators = mutableListOf<CodeGeneratorService>()

            while (services.hasNext()) {
                val service = services.next()
                generators.add(service)
                logger.info("  - ${service.name}")
            }

            if (generators.isEmpty()) {
                logger.warn("ServiceLoaderProcessor: No CodeGeneratorService implementations found!")
            } else {
                // Generate a file that lists all discovered services
                generateServiceRegistry(generators)
            }

        } catch (e: Exception) {
            logger.error("ServiceLoaderProcessor: Error loading services", null as KSNode?)
        }

        // Process all files to demonstrate service usage
        val files = resolver.getAllFiles()
        files.forEach { file ->
            processFile(file)
        }

        return emptyList()
    }

    private fun processFile(file: KSFile) {
        file.declarations.forEach { declaration ->
            when (declaration) {
                is KSClassDeclaration -> {
                    val className = declaration.simpleName.asString()

                    // Load services again for each class to show it works consistently
                    try {
                        val serviceLoader = ServiceLoader.load(CodeGeneratorService::class.java)
                        serviceLoader.forEach { service ->
                            if (service.supports(className)) {
                                val generatedCode = service.generate(className)
                                generateCodeFile(declaration, service.name, generatedCode)
                            }
                        }
                    } catch (e: Exception) {
                        logger.error("Error processing class $className", null as KSNode?)
                    }
                }
            }
        }
    }

    private fun generateServiceRegistry(services: List<CodeGeneratorService>) {
        val file = codeGenerator.createNewFile(
            Dependencies(true),
            "site.addzero.generated",
            "ServiceRegistry"
        )

        file.use {
            it.writer().use { writer ->
                writer.write("""
                    // Generated by ServiceLoaderProcessor
                    package site.addzero.generated

                    object ServiceRegistry {
                        val availableServices = listOf<String>(
                """.trimIndent())

                services.forEach { service ->
                    writer.write("\n                            \"${service.name}\",")
                }

                writer.write("""
                        )

                        fun getServiceNames(): List<String> = availableServices

                        fun printAllServices() {
                            println("Discovered services via ServiceLoader:")
                            availableServices.forEach { item ->
                                println("  - " + item)
                            }
                        }
                    }
                """.trimIndent())
            }
        }
    }

    private fun generateCodeFile(
        classDeclaration: KSClassDeclaration,
        generatorName: String,
        generatedCode: String
    ) {
        val className = classDeclaration.simpleName.asString()
        val fileName = "${className}_${generatorName}"

        val file = codeGenerator.createNewFile(
            Dependencies(true),
            "site.addzero.generated",
            fileName
        )

        file.use {
            it.writer().use { writer ->
                writer.write("""
                    // Generated by $generatorName
                    package site.addzero.generated

                    // Code generated for: $className
                    $generatedCode
                """.trimIndent())
            }
        }
    }

    override fun finish() {
        logger.info("ServiceLoaderProcessor: Processing finished")
    }

    override fun onError() {
        logger.error("ServiceLoaderProcessor: Processing completed with errors")
    }
}

/**
 * Provider for ServiceLoaderProcessor
 */
class ServiceLoaderProcessorProvider : SymbolProcessorProvider {
    override fun create(
        environment: SymbolProcessorEnvironment
    ): SymbolProcessor {
        return ServiceLoaderProcessor(environment)
    }
}