package site.addzero.ksp.serviceloader

/**
 * Consumer's custom implementation of CodeGeneratorService
 */
class CustomCodeGenerator : CodeGeneratorService {
    override val name = "CustomGenerator"

    override fun generate(context: String): String {
        return """
            // Generated by CustomCodeGenerator
            fun custom${context}() {
                println("This is custom generated code for $context")
                println("Generated at: ${System.currentTimeMillis()}")
            }
        """.trimIndent()
    }

    override fun supports(context: String): Boolean {
        // Support all contexts that start with "Custom" or "Test"
        return context.startsWith("Custom") || context.startsWith("Test") || context.endsWith("Class")
    }
}