// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A tool call representing a request to create, delete, or update files using diff patches.
 */
@Serializable
data class ApplyPatchToolCallItemParam(
    /**
     * The type of the item. Always `apply_patch_call`.
     */
    val type: String = "apply_patch_call",
    val id: String? = null,
    /**
     * The unique ID of the apply patch tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The status of the apply patch tool call. One of `in_progress` or `completed`.
     */
    val status: site.addzero.api.openai.models.ApplyPatchCallStatusParam,
    /**
     * The specific create, delete, or update instruction for the apply_patch tool call.
     */
    val operation: site.addzero.api.openai.models.ApplyPatchOperationParam
)
