// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The output emitted by an apply patch tool call.
 */
@Serializable
data class ApplyPatchToolCallOutput(
    /**
     * The type of the item. Always `apply_patch_call_output`.
     */
    val type: String = "apply_patch_call_output",
    /**
     * The unique ID of the apply patch tool call output. Populated when this item is returned via API.
     */
    val id: String,
    /**
     * The unique ID of the apply patch tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The status of the apply patch tool call output. One of `completed` or `failed`.
     */
    val status: site.addzero.api.openai.models.ApplyPatchCallOutputStatus,
    val output: String? = null,
    /**
     * The ID of the entity that created this tool call output.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
