// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A tool call that applies file diffs by creating, deleting, or updating files.
 */
@Serializable
data class ApplyPatchToolCall(
    /**
     * The type of the item. Always `apply_patch_call`.
     */
    val type: String = "apply_patch_call",
    /**
     * The unique ID of the apply patch tool call. Populated when this item is returned via API.
     */
    val id: String,
    /**
     * The unique ID of the apply patch tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The status of the apply patch tool call. One of `in_progress` or `completed`.
     */
    val status: site.addzero.api.openai.models.ApplyPatchCallStatus,
    /**
     * One of the create_file, delete_file, or update_file operations applied via apply_patch.
     */
    val operation: JsonElement,
    /**
     * The ID of the entity that created this tool call.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
