// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The streamed output emitted by an apply patch tool call.
 */
@Serializable
data class ApplyPatchToolCallOutputItemParam(
    /**
     * The type of the item. Always `apply_patch_call_output`.
     */
    val type: String = "apply_patch_call_output",
    val id: String? = null,
    /**
     * The unique ID of the apply patch tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The status of the apply patch tool call output. One of `completed` or `failed`.
     */
    val status: site.addzero.api.openai.models.ApplyPatchCallOutputStatusParam,
    val output: String? = null
)
