// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * If the audio output modality is requested, this object contains data about the audio response from
 * the model. [Learn more](/docs/guides/audio).
 */
@Serializable
data class ChatCompletionResponseMessageAudio(
    /**
     * Unique identifier for this audio response.
     */
    val id: String,
    /**
     * The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the
     * server for use in multi-turn conversations.
     */
    @SerialName("expires_at")
    val expiresAt: Long,
    /**
     * Base64 encoded audio bytes generated by the model, in the format specified in the request.
     */
    val data: String,
    /**
     * Transcript of the audio generated by the model.
     */
    val transcript: String
)
