// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * Refusal content part
 */
@Serializable
data class ChatCompletionRequestMessageContentPartRefusal(
    /**
     * The type of the content part.
     */
    val type: String,
    /**
     * The refusal message generated by the model.
     */
    val refusal: String
)
