// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * The custom tool that the model called.
 */
@Serializable
data class ChatCompletionMessageCustomToolCallCustom(
    /**
     * The name of the custom tool to call.
     */
    val name: String,
    /**
     * The input for the custom tool call generated by the model.
     */
    val input: String
)
