// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class ChatCompletionMessageListDataItem(
    val content: String?,
    val refusal: String?,
    @SerialName("tool_calls")
    val toolCalls: site.addzero.api.openai.models.ChatCompletionMessageToolCalls? = null,
    /**
     * Annotations for the message, when applicable, as when using the [web search
     * tool](/docs/guides/tools-web-search?api-mode=chat).
     */
    val annotations: List<site.addzero.api.openai.models.ChatCompletionMessageListDataItemAnnotation>? = null,
    /**
     * The role of the author of this message.
     */
    val role: String,
    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called,
     * as generated by the model.
     */
    @SerialName("function_call")
    val functionCall: site.addzero.api.openai.models.ChatCompletionMessageListDataItemFunctionCall? = null,
    val audio: site.addzero.api.openai.models.ChatCompletionMessageListDataItemAudio? = null,
    /**
     * The identifier of the chat message.
     */
    val id: String,
    @SerialName("content_parts")
    val contentParts: List<JsonElement>? = null
)
