// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A chat completion delta generated by streamed model responses.
 */
@Serializable
data class ChatCompletionStreamResponseDelta(
    val content: String? = null,
    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called,
     * as generated by the model.
     */
    @SerialName("function_call")
    val functionCall: site.addzero.api.openai.models.ChatCompletionStreamResponseDeltaFunctionCall? = null,
    @SerialName("tool_calls")
    val toolCalls: List<site.addzero.api.openai.models.ChatCompletionMessageToolCallChunk>? = null,
    /**
     * The role of the author of this message.
     */
    val role: String? = null,
    val refusal: String? = null
)
