// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called,
 * as generated by the model.
 */
@Serializable
data class ChatCompletionMessageListDataItemFunctionCall(
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the
     * model does not always generate valid JSON, and may hallucinate parameters not defined by your
     * function schema. Validate the arguments in your code before calling your function.
     */
    val arguments: String,
    /**
     * The name of the function to call.
     */
    val name: String
)
