// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Breakdown of tokens used in a completion.
 */
@Serializable
data class CompletionUsageCompletionTokensDetails(
    /**
     * When using Predicted Outputs, the number of tokens in the prediction that appeared in the
     * completion.
     */
    @SerialName("accepted_prediction_tokens")
    val acceptedPredictionTokens: Int? = 0,
    /**
     * Audio input tokens generated by the model.
     */
    @SerialName("audio_tokens")
    val audioTokens: Int? = 0,
    /**
     * Tokens generated by the model for reasoning.
     */
    @SerialName("reasoning_tokens")
    val reasoningTokens: Int? = 0,
    /**
     * When using Predicted Outputs, the number of tokens in the prediction that did not appear in the
     * completion. However, like reasoning tokens, these tokens are still counted in the total completion
     * tokens for purposes of billing, output, and context window limits.
     */
    @SerialName("rejected_prediction_tokens")
    val rejectedPredictionTokens: Int? = 0
)
