// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A compaction item generated by the [`v1/responses/compact` API](/docs/api-
 * reference/responses/compact).
 */
@Serializable
data class CompactionSummaryItemParam(
    val id: String? = null,
    /**
     * The type of the item. Always `compaction`.
     */
    val type: String = "compaction",
    /**
     * The encrypted content of the compaction summary.
     */
    @SerialName("encrypted_content")
    val encryptedContent: String
)
