// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A compaction item generated by the [`v1/responses/compact` API](/docs/api-
 * reference/responses/compact).
 */
@Serializable
data class CompactionBody(
    /**
     * The type of the item. Always `compaction`.
     */
    val type: String = "compaction",
    /**
     * The unique ID of the compaction item.
     */
    val id: String,
    /**
     * The encrypted content that was produced by compaction.
     */
    @SerialName("encrypted_content")
    val encryptedContent: String,
    /**
     * The identifier of the actor that created the item.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
