// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class CreateMessageRequest(
    /**
     * The role of the entity that is creating the message. Allowed values include: - `user`: Indicates the
     * message is sent by an actual user and should be used in most cases to represent user-generated
     * messages. - `assistant`: Indicates the message is generated by the assistant. Use this value to
     * insert messages from the assistant into the conversation.
     */
    val role: String,
    val content: JsonElement,
    val attachments: List<site.addzero.api.openai.models.CreateMessageRequestAttachment>? = null,
    val metadata: site.addzero.api.openai.models.Metadata? = null
)
