// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CreateEmbeddingResponse(
    /**
     * The list of embeddings generated by the model.
     */
    val data: List<site.addzero.api.openai.models.Embedding>,
    /**
     * The name of the model used to generate the embedding.
     */
    val model: String,
    /**
     * The object type, which is always "list".
     */
    @SerialName("object")
    val objectType: String,
    /**
     * The usage information for the request.
     */
    val usage: site.addzero.api.openai.models.CreateEmbeddingResponseUsage
)
