// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A call to a custom tool created by the model.
 */
@Serializable
data class CustomToolCall(
    /**
     * The type of the custom tool call. Always `custom_tool_call`.
     */
    val type: String,
    /**
     * The unique ID of the custom tool call in the OpenAI platform.
     */
    val id: String? = null,
    /**
     * An identifier used to map this custom tool call to a tool call output.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The namespace of the custom tool being called.
     */
    val namespace: String? = null,
    /**
     * The name of the custom tool being called.
     */
    val name: String,
    /**
     * The input for the custom tool call generated by the model.
     */
    val input: String
)
