// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * ResponseCustomToolCallOutputItem
 */
@Serializable
data class CustomToolCallOutputResource(
    /**
     * The type of the custom tool call output. Always `custom_tool_call_output`.
     */
    val type: String,
    /**
     * The unique ID of the custom tool call output in the OpenAI platform.
     */
    val id: String? = null,
    /**
     * The call ID, used to map this custom tool call output to a custom tool call.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The output from the custom tool call generated by your code. Can be a string or an list of output
     * content.
     */
    val output: JsonElement,
    /**
     * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
     * returned via API.
     */
    val status: site.addzero.api.openai.models.FunctionCallOutputStatusEnum,
    /**
     * The identifier of the actor that created the item.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
