// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ResponseCustomToolCallItem
 */
@Serializable
data class CustomToolCallResource(
    /**
     * The type of the custom tool call. Always `custom_tool_call`.
     */
    val type: String,
    /**
     * The unique ID of the custom tool call in the OpenAI platform.
     */
    val id: String? = null,
    /**
     * An identifier used to map this custom tool call to a tool call output.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The namespace of the custom tool being called.
     */
    val namespace: String? = null,
    /**
     * The name of the custom tool being called.
     */
    val name: String,
    /**
     * The input for the custom tool call generated by the model.
     */
    val input: String,
    /**
     * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
     * returned via API.
     */
    val status: site.addzero.api.openai.models.FunctionCallStatus,
    /**
     * The identifier of the actor that created the item.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
