// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A message input to the model with a role indicating instruction following hierarchy. Instructions
 * given with the `developer` or `system` role take precedence over instructions given with the `user`
 * role. Messages with the `assistant` role are presumed to have been generated by the model in
 * previous interactions.
 */
@Serializable
data class EasyInputMessage(
    /**
     * The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
     */
    val role: String,
    /**
     * Text, image, or audio input to the model, used to generate a response. Can also contain previous
     * assistant responses.
     */
    val content: JsonElement,
    val phase: site.addzero.api.openai.models.MessagePhase? = null,
    /**
     * The type of the message input. Always `message`.
     */
    val type: String? = null
)
