// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * A message input to the model with a role indicating instruction following hierarchy. Instructions
 * given with the `developer` or `system` role take precedence over instructions given with the `user`
 * role. Messages with the `assistant` role are presumed to have been generated by the model in
 * previous interactions.
 */
@Serializable
data class EvalItem(
    /**
     * The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
     */
    val role: String,
    val content: site.addzero.api.openai.models.EvalItemContent,
    /**
     * The type of the message input. Always `message`.
     */
    val type: String? = null
)
