// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The output of a function tool call.
 */
@Serializable
data class FunctionToolCallOutput(
    /**
     * The unique ID of the function tool call output. Populated when this item is returned via API.
     */
    val id: String? = null,
    /**
     * The type of the function tool call output. Always `function_call_output`.
     */
    val type: String,
    /**
     * The unique ID of the function tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The output from the function call generated by your code. Can be a string or an list of output
     * content.
     */
    val output: JsonElement,
    /**
     * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
     * returned via API.
     */
    val status: String? = null
)
