// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A tool representing a request to execute one or more shell commands.
 */
@Serializable
data class FunctionShellCallItemParam(
    val id: String? = null,
    /**
     * The unique ID of the shell tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The type of the item. Always `shell_call`.
     */
    val type: String = "shell_call",
    /**
     * The shell commands and limits that describe how to run the tool call.
     */
    val action: site.addzero.api.openai.models.FunctionShellActionParam,
    val status: site.addzero.api.openai.models.FunctionShellCallItemStatus? = null,
    val environment: JsonElement? = null
)
