// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The output of a shell tool call that was emitted.
 */
@Serializable
data class FunctionShellCallOutput(
    /**
     * The type of the shell call output. Always `shell_call_output`.
     */
    val type: String = "shell_call_output",
    /**
     * The unique ID of the shell call output. Populated when this item is returned via API.
     */
    val id: String,
    /**
     * The unique ID of the shell tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The status of the shell call output. One of `in_progress`, `completed`, or `incomplete`.
     */
    val status: site.addzero.api.openai.models.FunctionShellCallOutputStatusEnum,
    /**
     * An array of shell call output contents
     */
    val output: List<site.addzero.api.openai.models.FunctionShellCallOutputContent>,
    @SerialName("max_output_length")
    val maxOutputLength: Int?,
    /**
     * The identifier of the actor that created the item.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
