// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The output of a function tool call.
 */
@Serializable
data class FunctionCallOutputItemParam(
    val id: String? = null,
    /**
     * The unique ID of the function tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The type of the function tool call output. Always `function_call_output`.
     */
    val type: String = "function_call_output",
    /**
     * Text, image, or file output of the function tool call.
     */
    val output: JsonElement,
    val status: site.addzero.api.openai.models.FunctionCallItemStatus? = null
)
