// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The streamed output items emitted by a shell tool call.
 */
@Serializable
data class FunctionShellCallOutputItemParam(
    val id: String? = null,
    /**
     * The unique ID of the shell tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The type of the item. Always `shell_call_output`.
     */
    val type: String = "shell_call_output",
    /**
     * Captured chunks of stdout and stderr output, along with their associated outcomes.
     */
    val output: List<site.addzero.api.openai.models.FunctionShellCallOutputContentParam>,
    val status: site.addzero.api.openai.models.FunctionShellCallItemStatus? = null,
    @SerialName("max_output_length")
    val maxOutputLength: Int? = null
)
