// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A tool call that executes one or more shell commands in a managed environment.
 */
@Serializable
data class FunctionShellCall(
    /**
     * The type of the item. Always `shell_call`.
     */
    val type: String = "shell_call",
    /**
     * The unique ID of the shell tool call. Populated when this item is returned via API.
     */
    val id: String,
    /**
     * The unique ID of the shell tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The shell commands and limits that describe how to run the tool call.
     */
    val action: site.addzero.api.openai.models.FunctionShellAction,
    /**
     * The status of the shell call. One of `in_progress`, `completed`, or `incomplete`.
     */
    val status: site.addzero.api.openai.models.FunctionShellCallStatus,
    val environment: JsonElement?,
    /**
     * The ID of the entity that created this tool call.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
