// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FunctionToolCallResource(
    /**
     * The unique ID of the function tool call.
     */
    val id: String? = null,
    /**
     * The type of the function tool call. Always `function_call`.
     */
    val type: String,
    /**
     * The unique ID of the function tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The namespace of the function to run.
     */
    val namespace: String? = null,
    /**
     * The name of the function to run.
     */
    val name: String,
    /**
     * A JSON string of the arguments to pass to the function.
     */
    val arguments: String,
    /**
     * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
     * returned via API.
     */
    val status: String? = null,
    /**
     * The identifier of the actor that created the item.
     */
    @SerialName("created_by")
    val createdBy: String? = null
)
