// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * For `gpt-image-1` only, the token usage information for the image generation.
 */
@Serializable
data class ImageGenUsage(
    /**
     * The number of tokens (images and text) in the input prompt.
     */
    @SerialName("input_tokens")
    val inputTokens: Int,
    /**
     * The total number of tokens (images and text) used for the image generation.
     */
    @SerialName("total_tokens")
    val totalTokens: Int,
    /**
     * The number of output tokens generated by the model.
     */
    @SerialName("output_tokens")
    val outputTokens: Int,
    @SerialName("output_tokens_details")
    val outputTokensDetails: site.addzero.api.openai.models.ImageGenOutputTokensDetails? = null,
    @SerialName("input_tokens_details")
    val inputTokensDetails: site.addzero.api.openai.models.ImageGenInputUsageDetails
)
