// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The output token details for the image generation.
 */
@Serializable
data class ImageGenOutputTokensDetails(
    /**
     * The number of image output tokens generated by the model.
     */
    @SerialName("image_tokens")
    val imageTokens: Int,
    /**
     * The number of text output tokens generated by the model.
     */
    @SerialName("text_tokens")
    val textTokens: Int
)
