// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the content or the URL of an image generated by the OpenAI API.
 */
@Serializable
data class Image(
    /**
     * The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and
     * only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
     */
    @SerialName("b64_json")
    val b64Json: String? = null,
    /**
     * When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to
     * `url` (default value). Unsupported for the GPT image models.
     */
    val url: String? = null,
    /**
     * For `dall-e-3` only, the revised prompt that was used to generate the image.
     */
    @SerialName("revised_prompt")
    val revisedPrompt: String? = null
)
