// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A tool call to run a command on the local shell.
 */
@Serializable
data class LocalShellToolCall(
    /**
     * The type of the local shell call. Always `local_shell_call`.
     */
    val type: String,
    /**
     * The unique ID of the local shell call.
     */
    val id: String,
    /**
     * The unique ID of the local shell tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,
    val action: site.addzero.api.openai.models.LocalShellExecAction,
    /**
     * The status of the local shell call.
     */
    val status: String
)
