// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * The output of a local shell tool call.
 */
@Serializable
data class LocalShellToolCallOutput(
    /**
     * The type of the local shell tool call output. Always `local_shell_call_output`.
     */
    val type: String,
    /**
     * The unique ID of the local shell tool call generated by the model.
     */
    val id: String,
    /**
     * A JSON string of the output of the local shell tool call.
     */
    val output: String,
    val status: String? = null
)
