// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * The refusal content generated by the assistant.
 */
@Serializable
data class MessageContentRefusalObject(
    /**
     * Always `refusal`.
     */
    val type: String,
    val refusal: String
)
