// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The response resource.
 */
@Serializable
data class RealtimeResponse(
    /**
     * The unique ID of the response, will look like `resp_1234`.
     */
    val id: String? = null,
    /**
     * The object type, must be `realtime.response`.
     */
    @SerialName("object")
    val objectType: String? = null,
    /**
     * The final status of the response (`completed`, `cancelled`, `failed`, or `incomplete`,
     * `in_progress`).
     */
    val status: String? = null,
    /**
     * Additional details about the status.
     */
    @SerialName("status_details")
    val statusDetails: site.addzero.api.openai.models.RealtimeResponseStatusDetails? = null,
    /**
     * The list of output items generated by the response.
     */
    val output: List<site.addzero.api.openai.models.RealtimeConversationItem>? = null,
    val metadata: site.addzero.api.openai.models.Metadata? = null,
    /**
     * Configuration for audio output.
     */
    val audio: site.addzero.api.openai.models.RealtimeResponseAudio? = null,
    /**
     * Usage statistics for the Response, this will correspond to billing. A Realtime API session will
     * maintain a conversation context and append new Items to the Conversation, thus output from previous
     * turns (text and audio tokens) will become the input for later turns.
     */
    val usage: site.addzero.api.openai.models.RealtimeResponseUsage? = null,
    /**
     * Which conversation the response is added to, determined by the `conversation` field in the
     * `response.create` event. If `auto`, the response will be added to the default conversation and the
     * value of `conversation_id` will be an id like `conv_1234`. If `none`, the response will not be added
     * to any conversation and the value of `conversation_id` will be `null`. If responses are being
     * triggered automatically by VAD the response will be added to the default conversation
     */
    @SerialName("conversation_id")
    val conversationId: String? = null,
    /**
     * The set of modalities the model used to respond, currently the only possible values are
     * `[\"audio\"]`, `[\"text\"]`. Audio output always include a text transcript. Setting the output to
     * mode `text` will disable audio output from the model.
     */
    @SerialName("output_modalities")
    val outputModalities: List<String>? = null,
    /**
     * Maximum number of output tokens for a single assistant response, inclusive of tool calls, that was
     * used in this response.
     */
    @SerialName("max_output_tokens")
    val maxOutputTokens: JsonElement? = null
)
