// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A function call item in a Realtime conversation.
 */
@Serializable
data class RealtimeConversationItemFunctionCall(
    /**
     * The unique ID of the item. This may be provided by the client or generated by the server.
     */
    val id: String? = null,
    /**
     * Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
     * item.
     */
    @SerialName("object")
    val objectType: String? = null,
    /**
     * The type of the item. Always `function_call`.
     */
    val type: String,
    /**
     * The status of the item. Has no effect on the conversation.
     */
    val status: String? = null,
    /**
     * The ID of the function call.
     */
    @SerialName("call_id")
    val callId: String? = null,
    /**
     * The name of the function being called.
     */
    val name: String,
    /**
     * The arguments of the function call. This is a JSON-encoded string representing the arguments passed
     * to the function, for example `{"arg1": "value1", "arg2": 42}`.
     */
    val arguments: String
)
