// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A system message in a Realtime conversation can be used to provide additional context or
 * instructions to the model. This is similar but distinct from the instruction prompt provided at the
 * start of a conversation, as system messages can be added at any point in the conversation. For major
 * changes to the conversation's behavior, use instructions, but for smaller updates (e.g. "the user is
 * now asking about a different topic"), use system messages.
 */
@Serializable
data class RealtimeConversationItemMessageSystem(
    /**
     * The unique ID of the item. This may be provided by the client or generated by the server.
     */
    val id: String? = null,
    /**
     * Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
     * item.
     */
    @SerialName("object")
    val objectType: String? = null,
    /**
     * The type of the item. Always `message`.
     */
    val type: String,
    /**
     * The status of the item. Has no effect on the conversation.
     */
    val status: String? = null,
    /**
     * The role of the message sender. Always `system`.
     */
    val role: String,
    /**
     * The content of the message.
     */
    val content: List<site.addzero.api.openai.models.RealtimeConversationItemMessageSystemContentItem>
)
