// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The response resource.
 */
@Serializable
data class RealtimeBetaResponse(
    /**
     * The unique ID of the response.
     */
    val id: String? = null,
    /**
     * The object type, must be `realtime.response`.
     */
    @SerialName("object")
    val objectType: String? = null,
    /**
     * The final status of the response (`completed`, `cancelled`, `failed`, or `incomplete`,
     * `in_progress`).
     */
    val status: String? = null,
    /**
     * Additional details about the status.
     */
    @SerialName("status_details")
    val statusDetails: site.addzero.api.openai.models.RealtimeBetaResponseStatusDetails? = null,
    /**
     * The list of output items generated by the response.
     */
    val output: List<site.addzero.api.openai.models.RealtimeConversationItem>? = null,
    val metadata: site.addzero.api.openai.models.Metadata? = null,
    /**
     * Usage statistics for the Response, this will correspond to billing. A Realtime API session will
     * maintain a conversation context and append new Items to the Conversation, thus output from previous
     * turns (text and audio tokens) will become the input for later turns.
     */
    val usage: site.addzero.api.openai.models.RealtimeBetaResponseUsage? = null,
    /**
     * Which conversation the response is added to, determined by the `conversation` field in the
     * `response.create` event. If `auto`, the response will be added to the default conversation and the
     * value of `conversation_id` will be an id like `conv_1234`. If `none`, the response will not be added
     * to any conversation and the value of `conversation_id` will be `null`. If responses are being
     * triggered by server VAD, the response will be added to the default conversation, thus the
     * `conversation_id` will be an id like `conv_1234`.
     */
    @SerialName("conversation_id")
    val conversationId: String? = null,
    /**
     * The voice the model used to respond. Current voice options are `alloy`, `ash`, `ballad`, `coral`,
     * `echo`, `sage`, `shimmer`, and `verse`.
     */
    val voice: site.addzero.api.openai.models.VoiceIdsShared? = null,
    /**
     * The set of modalities the model used to respond. If there are multiple modalities, the model will
     * pick one, for example if `modalities` is `["text", "audio"]`, the model could be responding in
     * either text or audio.
     */
    val modalities: List<String>? = null,
    /**
     * The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.
     */
    @SerialName("output_audio_format")
    val outputAudioFormat: String? = null,
    /**
     * Sampling temperature for the model, limited to [0.6, 1.2]. Defaults to 0.8.
     */
    val temperature: Double? = null,
    /**
     * Maximum number of output tokens for a single assistant response, inclusive of tool calls, that was
     * used in this response.
     */
    @SerialName("max_output_tokens")
    val maxOutputTokens: JsonElement? = null
)
