// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A user message item in a Realtime conversation.
 */
@Serializable
data class RealtimeConversationItemMessageUser(
    /**
     * The unique ID of the item. This may be provided by the client or generated by the server.
     */
    val id: String? = null,
    /**
     * Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
     * item.
     */
    @SerialName("object")
    val objectType: String? = null,
    /**
     * The type of the item. Always `message`.
     */
    val type: String,
    /**
     * The status of the item. Has no effect on the conversation.
     */
    val status: String? = null,
    /**
     * The role of the message sender. Always `user`.
     */
    val role: String,
    /**
     * The content of the message.
     */
    val content: List<site.addzero.api.openai.models.RealtimeConversationItemMessageUserContentItem>
)
