// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.Serializable

/**
 * Parameters required to initiate a realtime call and receive the SDP answer needed to complete a
 * WebRTC peer connection. Provide an SDP offer generated by your client and optionally configure the
 * session that will answer the call.
 */
@Serializable
data class RealtimeCallCreateRequest(
    /**
     * WebRTC Session Description Protocol (SDP) offer generated by the caller.
     */
    val sdp: String,
    /**
     * Optional session configuration to apply before the realtime session is created. Use the same
     * parameters you would send in a [`create client secret`](/docs/api-reference/realtime-
     * sessions/create-realtime-client-secret) request.
     */
    val session: site.addzero.api.openai.models.RealtimeCallCreateRequestSession? = null
)
