// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A function call output item in a Realtime conversation.
 */
@Serializable
data class RealtimeConversationItemFunctionCallOutput(
    /**
     * The unique ID of the item. This may be provided by the client or generated by the server.
     */
    val id: String? = null,
    /**
     * Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
     * item.
     */
    @SerialName("object")
    val objectType: String? = null,
    /**
     * The type of the item. Always `function_call_output`.
     */
    val type: String,
    /**
     * The status of the item. Has no effect on the conversation.
     */
    val status: String? = null,
    /**
     * The ID of the function call this output is for.
     */
    @SerialName("call_id")
    val callId: String,
    /**
     * The output of the function call, this is free text and can contain any information or simply be
     * empty.
     */
    val output: String
)
