// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
package site.addzero.api.openai.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The response object
 */
@Serializable
data class Response(
    val metadata: site.addzero.api.openai.models.Metadata? = null,
    @SerialName("top_logprobs")
    val topLogprobs: Int? = null,
    val temperature: Double? = null,
    @SerialName("top_p")
    val topP: Double? = null,
    /**
     * This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key`
     * instead to maintain caching optimizations. A stable identifier for your end-users. Used to boost
     * cache hit rates by better bucketing similar requests and to help OpenAI detect and prevent abuse.
     * [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
     */
    val user: String? = null,
    /**
     * A stable identifier used to help detect users of your application that may be violating OpenAI's
     * usage policies. The IDs should be a string that uniquely identifies each user, with a maximum length
     * of 64 characters. We recommend hashing their username or email address, in order to avoid sending us
     * any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
     */
    @SerialName("safety_identifier")
    val safetyIdentifier: String? = null,
    /**
     * Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces
     * the `user` field. [Learn more](/docs/guides/prompt-caching).
     */
    @SerialName("prompt_cache_key")
    val promptCacheKey: String? = null,
    @SerialName("service_tier")
    val serviceTier: site.addzero.api.openai.models.ServiceTier? = null,
    @SerialName("prompt_cache_retention")
    val promptCacheRetention: String? = null,
    @SerialName("previous_response_id")
    val previousResponseId: String? = null,
    /**
     * Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a wide range of models
     * with different capabilities, performance characteristics, and price points. Refer to the [model
     * guide](/docs/models) to browse and compare available models.
     */
    val model: site.addzero.api.openai.models.ModelIdsResponses? = null,
    val reasoning: site.addzero.api.openai.models.Reasoning? = null,
    val background: Boolean? = null,
    @SerialName("max_tool_calls")
    val maxToolCalls: Int? = null,
    val text: site.addzero.api.openai.models.ResponseTextParam? = null,
    val tools: site.addzero.api.openai.models.ToolsArray? = null,
    @SerialName("tool_choice")
    val toolChoice: site.addzero.api.openai.models.ToolChoiceParam? = null,
    val prompt: site.addzero.api.openai.models.Prompt? = null,
    val truncation: String? = null,
    /**
     * Unique identifier for this Response.
     */
    val id: String,
    /**
     * The object type of this resource - always set to `response`.
     */
    @SerialName("object")
    val objectType: String,
    /**
     * The status of the response generation. One of `completed`, `failed`, `in_progress`, `cancelled`,
     * `queued`, or `incomplete`.
     */
    val status: String? = null,
    /**
     * Unix timestamp (in seconds) of when this Response was created.
     */
    @SerialName("created_at")
    val createdAt: Double,
    @SerialName("completed_at")
    val completedAt: Double? = null,
    val error: site.addzero.api.openai.models.ResponseError?,
    @SerialName("incomplete_details")
    val incompleteDetails: site.addzero.api.openai.models.ResponseIncompleteDetails?,
    /**
     * An array of content items generated by the model. - The length and order of items in the `output`
     * array is dependent on the model's response. - Rather than accessing the first item in the `output`
     * array and assuming it's an `assistant` message with the content generated by the model, you might
     * consider using the `output_text` property where supported in SDKs.
     */
    val output: List<site.addzero.api.openai.models.OutputItem>,
    val instructions: JsonElement?,
    @SerialName("output_text")
    val outputText: String? = null,
    val usage: site.addzero.api.openai.models.ResponseUsage? = null,
    /**
     * Whether to allow the model to run tool calls in parallel.
     */
    @SerialName("parallel_tool_calls")
    val parallelToolCalls: Boolean = true,
    val conversation: site.addzero.api.openai.models.Conversation2? = null,
    @SerialName("max_output_tokens")
    val maxOutputTokens: Int? = null
)
